### ISSUE TITLE
Add Logging support for SLF4J

### ISSUE THREAD

**Issue by meg23** [ESAPI/esapi-java-legacy#129]
_From [ps.gr...@gmail.com](https://code.google.com/u/114075484593062071800/) on April 27, 2010 03:09:02_

SLF4J is the next generation logging framework replacing commons logging and 
simplifies the complicated class loading used by commons logging(which normal 
breaks in Websphere). You can use a bridge to intercept log4j calls and 
direct these to SLF4J but feel it would be better to natively support SLF4J 
out of the box in ESAPI.

_Original issue: http://code.google.com/p/owasp-esapi-java/issues/detail?id=119_

**Comment by zhangshifeng** [comment]
@CarvalhoLeonardo and @jonesde has done [some work](https://github.com/moqui/moqui-framework/tree/master/framework/patches/esapi) on this issue, please give some advice.

**Comment by jeremiahjstacey** [comment]
Just to clarify the intent of this issue, are we looking to replace/upgrade the existing log4j to slf4j or simply add slf4j along side the log4j capabilities?

**Comment by xeno6696** [comment]
It should be replace.  Though, you get log4j compatability for free with slf4j.

**Comment by kwwall** [comment]
As long as we keep the ESAPI logging interfaces the same, I think we can
just support SLF4J and J.U.L. and get the log4j support via SLF4J.

@xeno6696, @chrisisbeef, or @planetlevel -- Do you think that is an
accurate assessment?

-kevin
--
Blog: http://off-the-wall-security.blogspot.com/  |  Twitter:  @KevinWWall
NSA: All your crypto bit are belong to us.

**Comment by xeno6696** [comment]
@jeremiahjstacey did some sleuthing.  And for a moment I was in agreement that because most implementations seem to offer automatic CRLF injection protection...

Except java.util.logging, and log4j.  

The reasoning behind changing ESAPI to use slf4J, is that we automatically gain access to defending *all* logging frameworks in current use.  JUL, log4j, and logback all have common slf4j bridge libraries[, with 4/5 github projects using slf4J as their primary interface.  ](http://blog.takipi.com/is-standard-java-logging-dead-log4j-vs-log4j2-vs-logback-vs-java-util-logging/)

The real reason for us to support slf4j, would be to allow applications that have already hooked themselves to our logging API, to be able to upgrade their Impls... if ESAPI supports slf4j, we allow any application that uses us to swap out for JUL, log4j, log4j2, and logback at will.  While the temptation is there to completely divest ourselves of logging due to the features of some of the other logging frameworks, I can tell you explicitly that a major financial application I worked on removed all slf4j logging simply to be consistent and only use ESAPI logging... which is tied to log4j, a REALLY defunct library in 2017.  

Once we provide ESAPI users with a common slf4j interface, we can sunset ESAPI logging when all logging frameworks adequately defend against CRLF injection and HTML injection.

**Comment by kwwall** [comment]
Sounds like a workable plan if we can keep the ESAPI Logger interface
backwards compatible. But if we break in there will be a lot of ticked off
devs. (I think we probably require configuration changes, just not code
changes.)

If feasible within a reasonable amount of time, let's do it. We can even
provide a SLF4J configuration that will use log4j to make the transition
smoother.

-kevin
--
Blog: http://off-the-wall-security.blogspot.com/  |  Twitter:  @KevinWWall
NSA: All your crypto bit are belong to us.

**Comment by xeno6696** [comment]
There's a nasty caveat here Kevin:  When I rolled back logging statements from slf4J to log4j, we had to remove all of the calls that slf4j had related to format strings.  So one major problem we open ourselves to is that all of the slf4j calls relating to log format strings are 3-arg calls when most log4j calls are 2-arg.  

There really isn't a way to tackle slf4j unless we choose to force all applications to adopt a different set of log format pattern rules with ESAPI than for the rest of their application.

**Comment by jeremiahjstacey** [comment]
I apologize, I'm still confused with what we actually want out of this right now.  

SLF4j is an API, it's a set of interfaces that bridge between an application and the configured logging implementation for an application.  Log4j is the current implementation extended by ESAPI, which provides another level of logging on top of log4j, common markers in the ESAPI-logs, and CRLF protection in the overridden Log4jLogger implementation.  

Those are the features that I believe we are looking to maintain in the SLF4j conversion, but we're talking about implementation-specific changes as well as API.  

The implementation extension is already pretty much handled by the existing ESAPI logger interface.  Clients can use that to decorate their logs with the extended API and they will then have access to the additional methods and levels of the ESAPI logging API.  We could make that easier by providing an EsapiSlf4jWrapper implementation that could format and forward message similar to how we're doing now.  Clients would still need to update code to use this class.  

We can dynamically inject the similar LogFactory-type lookup for SLF4j to find the ESAPI version, but then we would have another layer of responsibility to find the actual delegate Logging impelemntation that we would be using. This introduces a possible race condition in the client's environment. In order for us to inject our log factory, we would need to use the same mechanism that is being used by log4j and logback to get their factories used.  I'm sure there's classpath magic that can be done to ensure ours is always found first, but as a dev I really don't care for that type of magic.  Assuming that our Log Factory does get loaded first, we then need to repeat what the slf4j tool just did to find the actual delegate so we can agnostically decorate that logger.

A more simple solution is for any client using SLF4j to provide a log appender for the log4j configuration that forwards log events from log4j to slf4j in their environment.  This does not resolve the need to have log4j on the path, but would reduce the log output and configurations. We may even be able to provide the appender implementation, but it would still require a configuration change in appropriate environments.

As far as the common markers and the CRLF handling goes, unless we create the log factory we do not have a way to affect the client implmentation through slf4j. SLF4j is designed to move the libarary away from the logging implementation, we're releasing control on that logging content by this switch.  We can provide helpful logging utilities that make the information available to the client, but I don't believe we have a clean way to guarantee that all logs will use this feature.

So, the most "integrated" solution is to create a LogFactory extension for SLF4J which clients need to guarantee loads before the implementaitons on thier paths.  If we do that, then we have control over the logger implementations and we should be able to seamlessly decorate all loggers at runtime, but I would fear the maintenance on this solution (I really don't like this one).  The second option would be to provide an SLF4J appender implementation to bridge our current logging of log4j to slf4j.  This still requires that clients configure their applications to use that appender for forwarding events. Third, we can possibly provide a EsapiSlf4J Log Decorator Factory which clients would need to invoke in-code to wrap the loggers they get from SLF4J.  This requires code changes to ensure all appropriate loggers are decorated, but would provide the ESAPI Logging API as well as some (if not all) of the implementaiton support currently offered.  The last thing I think we can do is provide a set of utilities for accessing the current data that ESAPI is logging, and allow clients to optionally use it in their logging statements.

I think that the right answer is most likely a combination of the above. I'm still trying to understand the end-state we're looking for with this effort at this point in time.  To do that, I've captured the list of things that I believe ESAPI logging (Log4J) offers right now:

 1: Internal ESAPI logging is captured by an SLF4J configured logging implementation
 2: The log4j dependency is removed from the esapi dependencies (from other comments in the ticket)
 3: Clients using ESAPI logging interact with instances of ESAPI Logger interface
 4: ESAPI Logs append common markers to all log events. ("SECURITY")
 5: ESAPI Logs append User Name to log events
 6: ESAPI logs append ESAPI Session information to log events.
 7: ESAPI logs append user's last host address to log events.
 8: ESAPI logs guard against CRLF.

(please let me know if these are incorrect or need extending)

Are we wanting SLF4j to do all of this?

**Comment by xeno6696** [comment]
9:  ESAPI logs can be configured to also encode for HTML entities.  

Your issue with implementation makes a lot more sense now, because we would have to include a default Impl of our own, which may or may not correlate with what the API consumer is using.

**Comment by jeremiahjstacey** [comment]
Thank you again for the html encoding point, I keep forgetting that.

And yes, that is my primary concern with attempting to extend slf4j.  It is possible to inject into the process, but it opens up a whole new can of worms for us and/or our users.  I'd be very concerned about the maintainability of that code over time.

**Comment by xeno6696** [comment]
So...

Anyone who switches to ESAPI logging in a legacy app already has to change all their call structures.  

The key flexibility we want to get to, is where legacy users who are using ESAPI logging can swap out their Impl to their heart's content.  

To restate what I think you're saying the problem is:

1.  ESAPI already specifies an API for logging
2.  slf4j also specifies an API for logging.  Here, you're worried that our API codes to SLF4J and will thusly have ESAPI Logging delegating to SLF4J which will then delegate to the target Impl.  

I think the direction you want is our use-case:

We want to be able to provide a secure API that can delegate to the top 5 logging frameworks, which can either be accomplished by:

1.)  Creating an ESAPI logging Impl for EACH library.  
2.)  Code to slf4J and allow developers to use our API through any of those other Impls.  

It seems kloogy because we have an interface, we're coding to another interface, and then picking arbitrary Impls.  

I'm open to ideas that would be more elegant than what we're proposing, but I personally think it would be much more work to create all of the Impls than it would be to code to slf4J and configure Impls, defaulting perhaps to log4j2

**Comment by kwwall** [comment]
Maybe I'm being naive here, but I think there is a path forward. Your seem to be assuming that that I am saying that the `org.owasp.esapi.Logger` interface must remain unchanged, but I'm not saying that at all. There is no reason that we can't add _new_ methods to that interface. E.g., in the extreme case, if one wanted to expose an SLF4J logger, one _could_ expose (though, note I am definitely **NOT** recommending this of course) the `org.slf4j.Logger` class through a new method such as `getSLF4JLogger()`. Now from an encapsulation model, that certainly is not advisable, but I'm using the extreme case to illustrate my point. Add whatever you need to the  `org.owasp.esapi.Logger` interface. And for the obsolete ones, we simply mark them as deprecated and clean them up in a future release. We just can't break any existing code using ESAPI's current Logger. (Also note that there is an additional incentive here; most of the other ESAPI components use ESAPI's logger and I doubt that any of us want to refactor that, even though with an IDE it probably would be pretty straightforward.)

Also, you might want to look at the [OWASP Security Logging project](https://github.com/javabeanz/owasp-security-logging). They support an interface like ESAPI's Logger and also SLF4J. You might get some implementation ideas from them.

**Comment by xeno6696** [comment]
From @jeremiahjstacey 

> Usage Example:
> 
> `org.slf4j.Logger logger = new
> SafeSLF4JLogger(org.slf4j.LoggerFactory.getLogger(MyClazz.class));`
> 
> 
> That's the most straight-forward solution we can have I think. I'd like
> it more if we could make this more generic:
> 
> SLF4JFormatLogger
> 
> 
> then use `Function<String, String>` to format the message...
> 
> 
> `new SLF4JFormatLogger(LoggerFactory.getLogger(MyClazz.class),
> Functions.then(cleanNewlines).then(encodeHTML).then(AppendUserData).then(AppendAppData));`
> 
> 
> but that can come later if it's worth chasing.

**Comment by xeno6696** [comment]
```
package org.owasp.esapi;

import org.slf4j.Logger;
import org.slf4j.Marker;

/**
 * FIXME:  Document intent of class.  General Function, purpose of creation, intended feature, etc.
 *  Why do people care this exists? 
 * @author Jeremiah
 * @since Aug 4, 2017
 *
 */
public class SafeSLF4JLogger implements Logger {

    
    private final Logger delegate;
    
    public SafeSLF4JLogger(Logger toGuard) {
        this.delegate = toGuard;
    }
    
    /**
     * Removes newline characters from the provided String then encodes it for HTML before returning the 'clean' version
     * to the caller.
     * 
     * @param message
     *            Original message to clean.
     * @return Cleaned message.
     */
    private final String cleanMessage(String message) {
        // ensure no CRLF injection into logs for forging records
        String clean = message.replace('\n', '_').replace('\r', '_');
        if (ESAPI.securityConfiguration().getLogEncodingRequired()) {
            clean = ESAPI.encoder().encodeForHTML(message);
            if (!message.equals(clean)) {
                clean += " (Encoded)";
            }
        }
        return clean;
    }

    /** {@inheritDoc} */
    @Override
    public void debug(Marker arg0, String arg1, Object arg2, Object arg3) {
        delegate.debug(arg0, cleanMessage(arg1), arg2, arg3);
    }

    /** {@inheritDoc} */
    @Override
    public void debug(Marker arg0, String arg1, Object... arg2) {
        delegate.debug(arg0, cleanMessage(arg1), arg2);
    }

    /** {@inheritDoc} */
    @Override
    public void debug(Marker arg0, String arg1, Object arg2) {
        delegate.debug(arg0, cleanMessage(arg1), arg2);
    }

    /** {@inheritDoc} */
    @Override
    public void debug(Marker arg0, String arg1, Throwable arg2) {
        delegate.debug(arg0, cleanMessage(arg1), arg2);
    }

    /** {@inheritDoc} */
    @Override
    public void debug(Marker arg0, String arg1) {
        delegate.debug(arg0, cleanMessage(arg1));
    }

    /** {@inheritDoc} */
    @Override
    public void debug(String arg0, Object arg1, Object arg2) {
        delegate.debug(cleanMessage(arg0), arg1, arg2);
    }

    /** {@inheritDoc} */
    @Override
    public void debug(String arg0, Object... arg1) {
        delegate.debug(cleanMessage(arg0), arg1);
    }

    /** {@inheritDoc} */
    @Override
    public void debug(String arg0, Object arg1) {
        delegate.debug(cleanMessage(arg0), arg1);
    }

    /** {@inheritDoc} */
    @Override
    public void debug(String arg0, Throwable arg1) {
        delegate.debug(cleanMessage(arg0), arg1);
    }

    /** {@inheritDoc} */
    @Override
    public void debug(String arg0) {
        delegate.debug(cleanMessage(arg0));
    }

    /** {@inheritDoc} */
    @Override
    public void error(Marker arg0, String arg1, Object arg2, Object arg3) {
        delegate.error(arg0, cleanMessage(arg1), arg2, arg3);
    }

    /** {@inheritDoc} */
    @Override
    public void error(Marker arg0, String arg1, Object... arg2) {
        delegate.error(arg0, cleanMessage(arg1), arg2);
    }

    /** {@inheritDoc} */
    @Override
    public void error(Marker arg0, String arg1, Object arg2) {
        delegate.error(arg0, cleanMessage(arg1), arg2);
    }

    /** {@inheritDoc} */
    @Override
    public void error(Marker arg0, String arg1, Throwable arg2) {
        delegate.error(arg0, cleanMessage(arg1), arg2);
    }

    /** {@inheritDoc} */
    @Override
    public void error(Marker arg0, String arg1) {
        delegate.error(arg0, cleanMessage(arg1));
    }

    /** {@inheritDoc} */
    @Override
    public void error(String arg0, Object arg1, Object arg2) {
        delegate.error(cleanMessage(arg0), arg1, arg2);
    }

    /** {@inheritDoc} */
    @Override
    public void error(String arg0, Object... arg1) {
        delegate.error(cleanMessage(arg0), arg1);
    }

    /** {@inheritDoc} */
    @Override
    public void error(String arg0, Object arg1) {
        delegate.error(cleanMessage(arg0), arg1);
    }

    /** {@inheritDoc} */
    @Override
    public void error(String arg0, Throwable arg1) {
        delegate.error(cleanMessage(arg0), arg1);
    }

    /** {@inheritDoc} */
    @Override
    public void error(String arg0) {
        delegate.error(cleanMessage(arg0));
    }

    /** {@inheritDoc} */
    @Override
    public String getName() {
        return delegate.getName();
    }

    /** {@inheritDoc} */
    @Override
    public void info(Marker arg0, String arg1, Object arg2, Object arg3) {
        delegate.info(arg0, cleanMessage(arg1), arg2, arg3);
    }

    /** {@inheritDoc} */
    @Override
    public void info(Marker arg0, String arg1, Object... arg2) {
        delegate.info(arg0, cleanMessage(arg1), arg2);
    }

    /** {@inheritDoc} */
    @Override
    public void info(Marker arg0, String arg1, Object arg2) {
        delegate.info(arg0, cleanMessage(arg1), arg2);
    }

    /** {@inheritDoc} */
    @Override
    public void info(Marker arg0, String arg1, Throwable arg2) {
        delegate.info(arg0, cleanMessage(arg1), arg2);
    }

    /** {@inheritDoc} */
    @Override
    public void info(Marker arg0, String arg1) {
        delegate.info(cleanMessage(arg1), arg1);
    }

    /** {@inheritDoc} */
    @Override
    public void info(String arg0, Object arg1, Object arg2) {
        delegate.info(cleanMessage(arg0), arg1, arg2);
    }

    /** {@inheritDoc} */
    @Override
    public void info(String arg0, Object... arg1) {
        delegate.info(cleanMessage(arg0), arg1);
    }

    /** {@inheritDoc} */
    @Override
    public void info(String arg0, Object arg1) {
        delegate.info(cleanMessage(arg0), arg1);
    }

    /** {@inheritDoc} */
    @Override
    public void info(String arg0, Throwable arg1) {
        delegate.info(cleanMessage(arg0), arg1);
    }

    /** {@inheritDoc} */
    @Override
    public void info(String arg0) {
        delegate.info(cleanMessage(arg0));
    }

    /** {@inheritDoc} */
    @Override
    public boolean isDebugEnabled() {
        return delegate.isDebugEnabled();
    }

    /** {@inheritDoc} */
    @Override
    public boolean isDebugEnabled(Marker arg0) {
        return delegate.isDebugEnabled(arg0);
    }

    /** {@inheritDoc} */
    @Override
    public boolean isErrorEnabled() {
        return delegate.isErrorEnabled();
    }

    /** {@inheritDoc} */
    @Override
    public boolean isErrorEnabled(Marker arg0) {
        return delegate.isErrorEnabled(arg0);
    }

    /** {@inheritDoc} */
    @Override
    public boolean isInfoEnabled() {
        return delegate.isInfoEnabled();
    }

    /** {@inheritDoc} */
    @Override
    public boolean isInfoEnabled(Marker arg0) {
        return delegate.isInfoEnabled(arg0);
    }

    /** {@inheritDoc} */
    @Override
    public boolean isTraceEnabled() {
        return delegate.isTraceEnabled();
    }

    /** {@inheritDoc} */
    @Override
    public boolean isTraceEnabled(Marker arg0) {
        return delegate.isTraceEnabled(arg0);
    }

    /** {@inheritDoc} */
    @Override
    public boolean isWarnEnabled() {
        return delegate.isWarnEnabled();
    }

    /** {@inheritDoc} */
    @Override
    public boolean isWarnEnabled(Marker arg0) {
        return delegate.isWarnEnabled(arg0);
    }

    /** {@inheritDoc} */
    @Override
    public void trace(Marker arg0, String arg1, Object arg2, Object arg3) {
        delegate.trace(arg0, cleanMessage(arg1), arg2, arg3);
    }

    /** {@inheritDoc} */
    @Override
    public void trace(Marker arg0, String arg1, Object... arg2) {
        delegate.trace(arg0, cleanMessage(arg1), arg2);
    }

    /** {@inheritDoc} */
    @Override
    public void trace(Marker arg0, String arg1, Object arg2) {
        delegate.trace(arg0, cleanMessage(arg1), arg2);
    }

    /** {@inheritDoc} */
    @Override
    public void trace(Marker arg0, String arg1, Throwable arg2) {
        delegate.trace(arg0, cleanMessage(arg1), arg2);
    }

    /** {@inheritDoc} */
    @Override
    public void trace(Marker arg0, String arg1) {
        delegate.trace(arg0, cleanMessage(arg1));
    }

    /** {@inheritDoc} */
    @Override
    public void trace(String arg0, Object arg1, Object arg2) {
        delegate.trace(cleanMessage(arg0), arg1, arg2);
    }

    /** {@inheritDoc} */
    @Override
    public void trace(String arg0, Object... arg1) {
        delegate.trace(cleanMessage(arg0), arg1);
    }

    /** {@inheritDoc} */
    @Override
    public void trace(String arg0, Object arg1) {
        delegate.trace(cleanMessage(arg0), arg1);
    }

    /** {@inheritDoc} */
    @Override
    public void trace(String arg0, Throwable arg1) {
        delegate.trace(cleanMessage(arg0), arg1);
    }

    /** {@inheritDoc} */
    @Override
    public void trace(String arg0) {
        delegate.trace(cleanMessage(arg0));
    }

    /** {@inheritDoc} */
    @Override
    public void warn(Marker arg0, String arg1, Object arg2, Object arg3) {
        delegate.warn(arg0, cleanMessage(arg1), arg2, arg3);
    }

    /** {@inheritDoc} */
    @Override
    public void warn(Marker arg0, String arg1, Object... arg2) {
        delegate.warn(arg0, cleanMessage(arg1), arg2);
    }

    /** {@inheritDoc} */
    @Override
    public void warn(Marker arg0, String arg1, Object arg2) {
        delegate.warn(arg0, cleanMessage(arg1), arg2);
    }

    /** {@inheritDoc} */
    @Override
    public void warn(Marker arg0, String arg1, Throwable arg2) {
        delegate.warn(arg0, cleanMessage(arg1), arg2);
    }

    /** {@inheritDoc} */
    @Override
    public void warn(Marker arg0, String arg1) {
        delegate.warn(arg0, cleanMessage(arg1));
    }

    /** {@inheritDoc} */
    @Override
    public void warn(String arg0, Object arg1, Object arg2) {
        delegate.warn(cleanMessage(arg0), arg1, arg2);
    }

    /** {@inheritDoc} */
    @Override
    public void warn(String arg0, Object... arg1) {
        delegate.warn(cleanMessage(arg0), arg1);
    }

    /** {@inheritDoc} */
    @Override
    public void warn(String arg0, Object arg1) {
        delegate.warn(cleanMessage(arg0), arg1);
    }
    
    /** {@inheritDoc} */
    @Override
    public void warn(String arg0, Throwable arg1) {
        delegate.warn(cleanMessage(arg0), arg1);
    }

    /** {@inheritDoc} */
    @Override
    public void warn(String arg0) {
        delegate.warn(cleanMessage(arg0));
    }

    

}

```

**Comment by jeremiahjstacey** [comment]
I'm not sure that this is entirely right.  There probably needs to be another method in here to clean the var-args as well, since any one of those could be a user-specified value.  To do that I would probably need to convert the Objects to Strings (via toString probably) and return the array of Strings to forward to the delegate.  I'm not sure what the side-effects of that would be, if SLF4j can use appenders or formatters based on Object type, then I could break functionality.  In short, the above mentioned code still needs work.

**Comment by jeremiahjstacey** [comment]
Doing a little more digging into the SLF4J API, I'm now certain the above-mentioned code won't work as intended.  The message is a customized format message that data can be inserted into.  The data that is inserted is the Object elements following the message.  I'm not sure of the formatting options for different data types supported by SLF4J, but I'm betting at this point it can treat numbers different than Strings.  That means that the umbrella solution above, even if applied to the correct Objects, would not be a workable solution.  It has potential to cripple the formatting capability of SLF4J by treating everything as a cleaned String.

**Comment by jeremiahjstacey** [comment]
More research.  It appears that the internal mechanism for slf4j only uses Object.toString() for formatted messages.  Original solution may be viable,  need to update it to account for the Objects as well as the message though.  May need to account for not altering the slf4j syntax {} for variable injection into the message.
Should the message be cleaned? If SLF4j is used as recommended, then all logs should be written as:
`logger.info("first value is: {}", value);`

If the end-user implemented string concatenation though, we have a different problem:
`logger.info("first value is: {}   Second value is " + second, first);`

May need a smarter solution for the message, but I think it needs to be scanned to account for the concat scenario.

**Comment by jeremiahjstacey** [comment]
I started down the path of formatting the message before forwarding it to the HTML Encoder, and then I realized that the Encoder already does it.  I went ahead and initialized a new HTML Encoder in the logger.  In the case of messages, the IMMUNE_LIST passed to the encoder adds the SLF4j Formatting context elements to the immune set.  Non-message content is still using the default encoder html implementation.

I've added some pre-optimization and wrapped all of the delegate logger calls with "is level enabled" checks.  Hopefully that should prevent performing excess String processing on data that will be discarded.

I believe the implementation is done, if this is an agreeable approach.  I'm going to be working on testing this next.

[SafeSLF4JLogger.txt](https://github.com/ESAPI/esapi-java-legacy/files/1202346/SafeSLF4JLogger.txt)

**Comment by kayzid** [comment]
I tried using the SafeSFL4JLogger in my java project but the Veracode scan still flags 
    delegate.debug(cleanMessage(arg0));
delegate.info(cleanMessage(arg0), arg1);
Why are these getting flagged? Is there any work around for this?

**Comment by xeno6696** [comment]
Firstly @kayzid, that was untested code.  Delete it.

Secondly, we are still discussing the path forward.

**Comment by kayzid** [comment]
ok, because I was thinking of doing something similar as we use Log4j with SFL4j.
 Is there any existing solution out there for ESAPI with Log4j and SFL4j?

**Comment by kwwall** [comment]
And thirdly @kayzid <https://github.com/kayzid>, even if this were ESAPI
production code, that's not how the Veracode SAST engine works (nor any
others that I'm aware of).

SAST engines generally have rules hard-coded in to them that _explicitly_
white-list recognize certain researched and approved "cleanse" routines,
and then if one of those cleanse routines are seen in a source-to-sink
taint path, the call stack is marked as untainted at that point.

Some SAST engines will allow you to extend the SAST engine by creating your
_own_ set of custom rules to be run, but I don't think Veracode is one of
those. Also, Veracode certainly would not have it there yet. If they were
going to do that, I think that they would at least wait for an _official_
release of ESAPI before adding it. If you need more details, I suggest you
talk to your Veracode contact.

**Comment by mmichalowicz** [comment]
This question may have to move to another location, however I am confused. Is OWASP ESAPI Logger an active project? Is the logger standalone or does it come along with the entire ESAPI bundle (for lack of better words). Documentation seems to reflect that OWASP ESAPI Logger is dead, however this thread discussing SLF4J support seems to indicate there is still activity with a logger.  Thanks!

**Comment by nickulet** [comment]
Hi guys, is there any solution in using ESAPI within a project using slf4j other than removing all slf4j logging and use ESAPI logging?

**Comment by xeno6696** [comment]
@nickulet

Up above I think Jeremiah offers a potential hack to do that involving Reflection.

**Comment by nickulet** [comment]
Hi Xeno6696. Can you enlighten me how I can use the SafeSLF4JLogger class in a project? Sorry I'm not that familiar with logging frameworks. Thanks for the help man.

**Comment by vprakashrao** [comment]
Are there plans to add SLF4J support in ESAPI or this has been shelved?

**Comment by jeremiahjstacey** [comment]
@xeno6696 I'll take another look.  I read back through the comments and the difficulty I described with the API cohesion still makes sense, but maybe I'll see something this time that I missed last time around.

**Comment by jeremiahjstacey** [comment]
https://github.com/jeremiahjstacey/esapi-java-legacy-dev/commit/5232e21036f2959875c7ec7996406f9692d8e5fe

https://github.com/jeremiahjstacey/esapi-java-legacy-dev/commit/938b8c8b78892d6b93ef911cc809df7fa1949dbc

@xeno6696 
I don't know if this approach will work, but it seemed plausible.  As noted in the commit messages, I have not tested this **at all**.

**Comment by kwwall** [comment]
If @jeremiahjstacey does get this to work, we ought to switch from log4j 1.2.17 to the latest log4j 2.x as log4j 1.x is not end-of-life. (Log4j 2.x is not 100% backwards compatible with 1.x, but maybe that's not an issue if we support SLF4J. Perhaps we could just refer people to https://logging.apache.org/log4j/2.x/manual/migration.html instead of trying to accommodate backward compatibility with log4j 1.x ourselves. Thoughts?)

**Comment by kwwall** [comment]
BTW, one reason it's important to migrate off log4j 1.2.17 to the latest log4j 2.x or whatever is because of CVE-2017-5645. While technically that really isn't exploitable in ESAPI given our default configuration of log4j.xml uses ConsoleAppender, it is still causing some to avoid ESAPI because it is getting flagged in Dependency Check, etc. Technically the description for CVE-2017-5645 as well as the associated CPEs only cover log4j 2.x, but at least my company isn't buying that. (Also, I told them that the deserialization issue is only with SocketAppender, not ConsoleAppender, like we use by default, but they were concerned that a developer could change ESAPI's log4j.xml to use SocketAppender. While there is a SocketAppender with log4j 1.2.17 (version we are currently referencing in our pom.xml), I haven't checked if it has the same Java deserialization issue with it, although it probably does and since 1.x is not longer supported, 1.2.17 probably is affected and no patch will ever likely be made for a later 1.x version.

**Comment by jeremiahjstacey** [comment]
Just wanted to offer an update, I think I'm making progress but uncovering some additional work I wasn't originally anticipating.  Latest changes have been pushed up to my fork.


https://github.com/jeremiahjstacey/esapi-java-legacy-dev/tree/slf4j_129 

I've *locally* updated my test scope to use the slf4j-log4j bridge at the current version:
```
<dependency>
  <groupId>org.slf4j</groupId>
  <artifactId>slf4j-log4j12</artifactId>
  <version>1.7.25</version>
  <scope>test</scope>
</dependency>
```

And I've also *locally* altered the  test-scope ESAPI.properties to use the new Slf4JLogFactory
```ESAPI.Logger=org.owasp.esapi.logging.slf4j.Slf4JLogFactory```

When running the tests, the target/unit-test.log file is still being generated with content.  I believe that is a scale of victory, but I am now seeing a new error in tests related to the Logger class resolution.

```: org.apache.log4j.Logger cannot be cast to org.owasp.esapi.Logger```

I am thinking this may be a runtime dependency resolution issue between the LogFactory in the bridge and Esapi's, but I haven't started to dig into it yet.

**Comment by kwwall** [comment]
@jeremiahjstacey I will take a look at this to see if I can figure it out, but the reason why I wanted to notify you was, since you have to tweak ESAPI's `pom.xml` file anyway to add SLF4J as a dependency, could you please make sure that we are using the latest versions of other dependencies as well? (If they don't build or tests fail, back it out and create a GitHub issue to note it, but I figure since you need to touch it anyhow, we might as well kill two birds with one stone.)

**Comment by jeremiahjstacey** [comment]
I currently believe that the cause of the cast exceptions is a combination of two things.  First, I altered the test-scope ESAPI.properties to default to the Slf4JLogFactory.   Second, both the Log4JLoggerTest and the JavaLoggerTest alter the state of the environment for their own executions.  After either of these tests run I will see the cast failures.  If both of these suites are ignored then everything runs through without failure.

It seems we cannot set the SLF4JLogFactory to the default in test scope, but that was not requested in this effort.   I am assuming that this is a consequence of those tests changing the logger type at runtime, and I do not believe this will be a problem in a production system.  If we decide later to alter the default logger for test scope, I believe those two tests will need to be refactored to not alter global state.

I believe this can be re-integrated and put to use, to the best of my current understanding.

---

I looked into the dependency updates, and I was able to make some changes there as well.  I only looked at the dependencies, and did not attempt/investigate the maven build plugin versions.

There were some caveats to this work.  I found two references where the later artifact version had removed classes.  I found the new home for those classes and changed the references to the new project and latest versions.  There was one project that I was unable to update because new API was added.  It is a 'provided' dependency used by the waf package.  I was not sure if the dependency scope changes the handling for that update -- do you still want another issue filed?

The specific project references and impacts are noted in my commit message.
Here is a link to the pom updates that I made.
https://github.com/jeremiahjstacey/esapi-java-legacy-dev/commit/a627f6d64809f4f570c9358c9ff335ed06949f47

**Comment by kwwall** [comment]
@jeremiahjstacey You wrote:

> I currently believe that the cause of the cast exceptions is a combination of two things. First, I altered the test-scope ESAPI.properties to default to the Slf4JLogFactory. Second, both the Log4JLoggerTest and the JavaLoggerTest alter the state of the environment for their own executions. After either of these tests run I will see the cast failures. If both of these suites are ignored then everything runs through without failure.

Rather than trying to permanently setting **ESAPI.Logge**r to `Slf4JLogFactory` in **src/test/resources/esapi/ESAPI.properties** and then having `Log4JLoggerTest` and `JavaLoggerTest` fail, I would instead suggest you write your SLF4J logger JUnit tests using `org.owasp.esapi.SecurityConfigurationWrapper`. I believe that we've used this in a few JUnit test cases to temporarily override settings in the test **ESAPI.properties** file. Give that a try. It's a little extra coding in your JUnit test, but if it works, it should avoid the failures in `Log4JLoggerTest` and `JavaLoggerTest`.

**Comment by jeremiahjstacey** [comment]
I had only made the ESAPI.properties change to verify that the SLF4JLogger will be resolved by the application at runtime.  As it stands, the code for the SLF4J logging behavior is fully tested, and has no reliance on other environmental factors.  The cast exceptions just caught me off guard, I was briefly concerned that I had incorrectly set up the SLF4J API.

I don't believe any further changes are needed for the test scope for this effort and the modifications I made to ESAPI.properties for verifying the runtime resolution of SLF4J Logging structures will not be committed.

**Comment by kwwall** [comment]
Now that I actually go back and look at them, it seems as though both `Log4JLoggerTest` and `JavaLoggerTest` were already configured to override ESAPI.Logger via **src/test/java/org/owasp/esapi/reference/UnitTestSecurityConfiguration.java**, so that's probably not what was causing the problem anyhow.

**Comment by kwwall** [comment]
Closed as per PR #446

**Comment by kirankumarlegend** [comment]
is their any timeline for a new release with this slf4j support

**Comment by kwwall** [comment]
I just got access to Sonatype earlier this week and have been busy with house issues. Still need to create release notes and not sure how long that will take so no definite date yet.

However, @kirankumarlegend other than a few JUnit tests, this slf4j support hasn't been well tested. Is there any chance that you could give it a shot using the latest ESAPI build based on what is on the 'develop' branch and let us know whether or not it works?
