### ISSUE TITLE
minimum-config deployment fails 

### ISSUE THREAD

**Issue by meg23** [ESAPI/esapi-java-legacy#157]
_From [saadsha...@gmail.com](https://code.google.com/u/100689809281794595676/) on September 14, 2010 15:14:47_

What steps will reproduce the problem? 1. extract ESAPI-2.0-rc7.zip into a folder
2. reference the ESAPI method ESAPI.encoder().encodeForHTML ( ...) in a JSP in an ear file
3. move the configuration, lib, and esapi-2.0_RC7-SNAPSHOT.jar folders extracted from 1 to be included in the ear file that contains the JSP where ESAPI is used
3. observe exception on JSP and the following in logs:
Attempting to load ESAPI.properties via file io.
Attempting to load ESAPI.properties via file io.
Not found in 'org.owasp.esapi.resources' directory or file not readable: C:\longAppDir\ESAPI.properties
Not found in SystemResource Directory/resourceDirectory: .esapi\ESAPI.properties
Not found in 'user.home' directory: C:\Documents and Settings\yourUser.esapi\ESAPI.properties
Loading ESAPI.properties via file io failed.
Attempting to load ESAPI.properties via the classpath.
ESAPI.properties could not be loaded by any means. fail. What is the expected output? What do you see instead? Validation should occur without an exception - ESAPI.properties should be found even with minimum configuration.  Or this should be explicitly stated in the install-guide.  The addition of -Dorg.owasp.esapi.resources to the startup args did not work as intended.  It also failed as the argument was added after debugging arguments, which for some reason caused it to not get picked up (debugged the source DefaultSecurityConfiguration and saw that customDirectory string was null). What version of the product are you using? On what operating system? esapi-2.0_RC7-SNAPSHOT.jar Please provide any additional information below. The fix:
Add "Class-Path: configuration/.esapi/" to the manifest in esapi-2.0_RC7-SNAPSHOT.jar:
Manifest-Version: 1.0
Class-Path: configuration/.esapi/
Created-By: 1.6.0_20 (Sun Microsystems Inc.)
Or at least this should be mentioned in the install-guide, along with the automatic addition of the argument to the startup args should be mentioned and done properly.

_Original issue: http://code.google.com/p/owasp-esapi-java/issues/detail?id=147_

**Comment by xeno6696** [comment]
In 2017, people will be adding esapi either via maven or gradle builds.  (Heck, even ant/ivy...)  

Closing.

**Comment by kwwall** [comment]
Again, this is an issue of not knowing where to put your `ESAPI.properties` file. I told the guy who is working on the ESAPI FAQ to make sure to include a question on that, but this has been answered on Stack Overflow probably at least a 1/2 dozen times. Maven doesn't really help you much here; not sure about Gradle; probably none do out of the box. Almost certainly you have to tell your application server where you dropped `ESAPI.properties`. Part of the problem is that there's a bunch of places that ESAPI looks for ESAPI.properties and it's only documented in the `DefaultSecurityConfiguration` Javadoc and most people don't think to look there. But I agree this should be closed.
