### ISSUE TITLE
DOMConfigurator is being used inappropriately in the ESAPIWebApplicationFirewallFilter

### ISSUE THREAD

**Issue by meg23** [ESAPI/esapi-java-legacy#173]
_From [manico.james@gmail.com](https://code.google.com/u/manico.james@gmail.com/) on November 01, 2010 00:21:35_

Please migrate this to the ESAPI logging framework.

_Original issue: http://code.google.com/p/owasp-esapi-java/issues/detail?id=163_

**Comment by kwwall** [comment]
@nahsra Any idea what the 'ask' is here? Asking you because @jmanico listed you as owner.

**Comment by xeno6696** [comment]
I'd say with 9yrs and no response since you asked, we can close this one out.

**Comment by kwwall** [comment]
@xeno6696 Well, sort of, but not because I asked that long ago. It was only since 2018 since I asked Arshan. However, if you look up the original Google Code link from the original issue on archive.org, you will see that all it says [there](https://web.archive.org/web/20130616225042/http://code.google.com/p/owasp-esapi-java/issues/detail?id=163) is "Please migrate this to the ESAPI logging framework."

So I started looking into this.  I looked in org.owasp.esapi.waf.ESAPIWebApplicationFirewallFilter and that class is already using ESAPI logging. So again, I'm not really sure what this means, but perhaps Arshan is not watching this repo so never saw the original question. I will try emailing him directly. He's generally pretty go about answering.

**Comment by kwwall** [comment]
Back on 3/12/2019, I emailed Arshan and asked him to look at this and his reply was:

> Hmm, no memory of that. Looking at the code, could it be that the WAF is using its own logging initializing based on some web.xml value, when it should be using ESAPIs?

I then replied to him that:

> While ESAPI has a default log4j.xml under the 'configuration' directory, we don't provide any default web.xml, so any logging file related parameters would have to be provided by the whomever is using the ESAPWebApplicationFirewallFilter class. So I can't see how this is an issue.
> We were thinking of closing this issue unless you can think of something that needs to be done for it.

And he did not reply back. Therefore, because no one seems to know what the 'ask' was for this, I am closing it.
