### ISSUE TITLE
UnInitialized esapi logging assumes logging to System.out/System.err - Make configurable/extensible

### ISSUE THREAD

**Issue by meg23** [ESAPI/esapi-java-legacy#198]
_From [Steve.Sp...@gmail.com](https://code.google.com/u/109473619041204502922/) on December 03, 2010 12:46:38_

Uninitialized logging calls logSpecial, which in turn calls System.out. This behavior should be configurable with an option to turn console logging off. Ideally, this behavior should be extensible so that a custom logging implementation can override the logSpecial method with a custom implementation.

Original email to esapi-user list: 

I'm having an issue with logging in esapi.

When my application is starting up, it initializes it's logging and does other things, then it loads esapi. The esapi logger is not initialized yet so it dumps a bunch of logging messages to System.out via the logSpecial() method.

What I would like is a way to configure esapi to disable console logging or to redirect console logging to another type of object which then could be used by my application that already has it's loggings system initialized.

This is the issue that I'm currently having. My server is a console-based app. Startup should look like this:

MyApp Service Starting
  License successfully validated
  Loading database schemas
    Database schema being created or updated for MyApp
  Finished loading database schemas
MyApp Service Started

Instead, it looks like this:

MyApp Service Starting
  License successfully validated
  Loading database schemas
    Database schema being created or updated for MyApp
  Finished loading database schemas
Attempting to load ESAPI.properties via file io.
Attempting to load ESAPI.properties via file io.
Found in 'org.owasp.esapi.resources' directory: C:\MyApp\conf\esapi\ESAPI.properties
Loaded 'ESAPI.properties' properties file
Attempting to load validation.properties via file io.
Attempting to load validation.properties via file io.
Found in 'org.owasp.esapi.resources' directory: C:\MyApp\conf\esapi\validation.properties
Loaded 'validation.properties' properties file
MyApp Service Started

Redirecting System.out and System.err to log4j (what my app uses) prior to esapi loading solves this issue, the problem then is that the last line "MyApp Service Started" never appears, which is critical.

_Original issue: http://code.google.com/p/owasp-esapi-java/issues/detail?id=188_

**Comment by kwwall** [comment]
This is really somewhat of a catch-22 situation. This verbose output that is refered to comes from the DefaultSecurityConfiguration class as it is searching for the correct ESAPI.properties and validation.properties files to use. The catch-22 is that ESAPI can use either log4j or java.util.logging, but it doesn't know which is being used until it finds and parses the ESAPI.properties file (which can be located in many different places).

Because of this, we can't use the regular ESAPI logging mechanism to control the log level as the ESAPI logger may not have been parsed yet.

Also, one of the biggest problems that new users to ESAPI ask about in Stack Exchange is how to get ESAPI to use the ESAPI.properties file that they _intend_ it to use. So because of that, I don't want the default to be silent or that will really excerbate that problem.

Some possibilities that may work is to disable output if a new System property is set to some value; e.g., if

    esapi.configuration.logmessages

is set to "quiet" or to "off", then don't log them. Alternately, there could be a static method provided on DefaultSecurityConfiguration; e.g.,

    DefaultSecurityConfiguration.disableConfigurationLogMessages(boolean flag)

I don't like that, but could live with it.

Lastly, we could prefix all the output with something like "***ESAPI: " to make it easily to filter out.

Thoughts?
-kevin

**Comment by xeno6696** [comment]
I prefer the token solution, as its trivial to "grep" away what you don't want.

**Comment by kwwall** [comment]
One can now set the System property "org.owasp.esapi.logSpecial.discard" to the value "true" to cause the logSpecial() method to discard all log messages.

**Comment by AsinusRex** [comment]
> One can now set the `System` property "**org.owasp.esapi.logSpecial.discard**" to the value `true` to cause the `logSpecial() `method to discard all log messages.

Can you please elaborate on this? I'd love to keep the output cleaner if possible. How would I set such a property?

**Comment by kwwall** [comment]
@xeno6696 - Actually that won't have any effect for this because this `System` property needs to be set _before_ the **ESAPI.properties** file is processed if you want to quiet the special logging that comes out.
@AsinusRex - I would just recommend adding a
&nbsp;&nbsp;&nbsp;&nbsp;`-Dorg.owasp.esapi.logSpecial.discard=true`
to your JVM arguments. That's how I've always done it.

But otherwise, there is not much we can do about this and given that logging misconfigurations are probably the most common misconfiguration in the **ESAPI.properties** file, I'm really reluctant to just remove the '`logSpecial`' calls, so I think this is the best we can do for the ESAPI 2.x releases. As a result, I am closing this GitHub issue.
