### ISSUE TITLE
SecurityWrapperResponse.createCookieHeader modification request

### ISSUE THREAD

**Issue by meg23** [ESAPI/esapi-java-legacy#232]
_From [manico.james@gmail.com](https://code.google.com/u/manico.james@gmail.com/) on May 05, 2011 19:15:19_

I'm trying to implement the SecurityWrapper filter in a java app and I'm running into an issue with the max-age.  IE just ignores the parameter, and Firefox/Chrome seem to treat Max-Age=-1 as equivalent to Max-Age=0.  Would it be possible to update the createCookieHeader() function in SecurityWrapperResponse.java to something like this:

private String createCookieHeader(String name, String value, int maxAge, String domain, String path, boolean secure) {
        // create the special cookie header instead of creating a Java cookie
        // Set-Cookie:<name>=<value>[; <name>=<value>][; expires=<date>][;
        // domain=<domain_name>][; path=<some_path>][; secure][;HttpOnly
        String header = name + "=" + value;
        if (maxAge >= 0) {
              header += "; Max-Age=" + maxAge;
        }
        if (domain != null) {
            header += "; Domain=" + domain;
        }
        if (path != null) {
            header += "; Path=" + path;
        }
        if ( secure || ESAPI.securityConfiguration().getForceSecureCookies() ) {
                     header += "; Secure";
        }
        if ( ESAPI.securityConfiguration().getForceHttpOnlyCookies() ) {
                     header += "; HttpOnly";
        }
        return header;
    }

Tyler Mathwich
Software Developer
Information Technology Dept.
State of North Dakota
(701) 328-6564

_Original issue: http://code.google.com/p/owasp-esapi-java/issues/detail?id=223_

**Comment by kwwall** [comment]
Ah the joys of working with non-compliant browsers. Will see if we can get this into the 2.3 release.

**Comment by kwwall** [comment]
I researched this because I wasn't sure if MSIE 8 was EOL or not. But as per https://www.microsoft.com/en-us/microsoft-365/windows/end-of-ie-support:

> Support ended 1/12/16 for Internet Explorer (IE) 10 and older. Security updates, compatibility fixes, and technical support continues for IE 11 on Windows 7, 8.1, and 10.

Given that all three of the browser versions mentioned here are now EOL, I personally do not think that we should try to add the 'expires' attribute. While I do not think that this enhancement would be this difficult to add, if one an application's users are using an unsupported browser that is almost certainly a bigger problem than whether they browser deletes certain cookies. (Any cookies concerned with authentication should be session cookies rather than persistent cookies anyway.)

Thus I propose 'wontfix' for this and that we simply close it. It may have been relevant when it was first created, but I don't think it is any longer. (Plus, I am not sure ESAPI should try to make up for browser deficiencies of browsers not conforming to standards.)

I will leave this open for 14 days (until 7/20) and if no serious objections are raised, I plan on closing this without addressing it.

**Comment by kwwall** [comment]
Also, I am dropping this to a low priority. I would think that the total browser market for IE6, IE7, and IE8 has got to be less than 2% or so by now, so this no longer rates a 'high'.

**Comment by kwwall** [comment]
Sent email to ESAPI Dev and ESAPI Users mailing lists soliciting feedback by 7/20/2019.

**Comment by kwwall** [comment]
Okay, it's way past 7/20 and I only had one comment back saying "close it". As noted in this post discussing[ this in the ESAPI Dev Google group](https://groups.google.com/a/owasp.org/forum/#!topic/esapi-project-users/DkEVFp3tbHQ), this is so old as I no longer think it is relevant. If someone disagrees, submit a tested PR, but we can't possibly support every ancient browser if for no other reason, there is no easy way for us to test him. (Unless you care to donate that old Win98 laptop you all are keeping in you dusty basements, under a pile of muddy boots and some an old tent or whatever. Note that _I've_ ever done that. I don't have any muddy boots and I think my old Win98 desktop is disassembled and the MB is mounted on my wall and I have no clue what happened to the hard drive. :)
