### ISSUE TITLE
KeyDerivationFunction::computeDerivedKey - possible security level mismatch

### ISSUE THREAD

**Issue by meg23** [ESAPI/esapi-java-legacy#245]
_From [noloa...@gmail.com](https://code.google.com/u/114558122492435650190/) on August 05, 2011 19:16:21_

KeyDerivationFunction::computeDerivedKey has a possible security level mismatch. See the discussion "KeyDerivationFunction: key derivation key size or range?" at https://lists.owasp.org/pipermail/owasp-esapi-c++/2011-August/000115.html .

_Original issue: http://code.google.com/p/owasp-esapi-java/issues/detail?id=238_

**Comment by kwwall** [comment]
Even though this is security related, I changed this to a 'low' priority because:

1. It does not affect the reference implementation of ESAPI crypto.
2. ESAPI crypto is rarely used in the business world.
3. A careful reading of this Javadoc would make it unlikely that someone is going to submit a 'keyDerivationKey' that is shorter than 'keySize'.

So essential this is a case of "defense in depth" more than anything.

**Comment by kwwall** [comment]
Closed via merged PR #506
