### ISSUE TITLE
JavascriptCodec is removing all backslashes

### ISSUE THREAD

**Issue by meg23** [ESAPI/esapi-java-legacy#259]
_From [david.al...@hraccess.com](https://code.google.com/u/100376573109526911240/) on November 15, 2011 04:31:15_

What steps will reproduce the problem? 1. String raw ="C:\\Documents and Settings\\Mario\\Desktop\\";
2. System.out.println(ESAPI.encoder().canonicalize(raw)); What is the expected output? What do you see instead? I expect the same as the input String because the input does not contain any javascript encoded char such as \r or \t

Instead I see this in the console :

C:Documents and SettingsMarioDesktop\ What version of the product are you using? On what operating system? ESAPI java 2.0.1 on Windows, Java 5 Does this issue affect only a specified browser or set of browsers? Nope. Please provide any additional information below. I've made a modification to JavascriptCodec, at the end of the method decodeCharacter() replacing :

// ignore the backslash and return the character
return second;

by :

// not an encoded character, return it
input.reset();
return null;

_Original issue: http://code.google.com/p/owasp-esapi-java/issues/detail?id=252_

**Comment by planetlevel** [comment]
I think we should close this without changes.  In JavaScript its legal to escape any character as itself.  \a -> a

--Jeff



On Tue, Jun 14, 2016 at 2:30 PM -0400, "Matt Seil" <notifications@github.com<mailto:notifications@github.com>> wrote:


@planetlevel<https://github.com/planetlevel> , @kwwall<https://github.com/kwwall> it looks here like the JavaScriptCodec just forgets to re-attach the backslash into the string when an escape hasn't been detected. Or are we purposefully NOT allowing any backslashes into the output?

-

**Comment by kwwall** [comment]
So question for all of you... in computer science, "canonical form" usually
means the normal or "standard" representation of some object. Often that is
represented by the simplest form. Seems like the confusion here is the
mixing of 2 different canonical forms: one being Javascript and the other
being a Windows path name. We should not let the latter confuse issues. The
example test case given used the latter, but the context was the latter,
hence the confusion. I think I'm leaning towards Jeff's reply, but first
let me ask, what would
     var normal = "C:\Users\kww\nl\tab".normalize();

return? Because I think that's what my intuition tells me to expect for
ESAPI 's Javascript canonicalization. (Note: I have not tried it and
honestly am not sure w/out testing it, which I am too lazy to do. If that
leaves the '\' characters in though, then i think ESAPI's Javascript
canonicalization should as well.)

-kevin
Sent from my Droid; please excuse typos.

**Comment by planetlevel** [comment]
Not sure I have the whole history here, so I may be confused.

Why are we using the JavaScript codec to canonicalize a windows path name?  The meaning here (to me) is pretty ambiguous.

"C:\Users\kww\nl\tab”

has a newline and a tab in it (obviously) when viewed through a JavaScript lens.  The ESAPI canonicalization process can be customized with a stack of codecs depending on which downstream environments the data is intended for.

FWIW, it looks like normalize() does not remove \ even for \t and \n.  But that’s not canonicalize to me.

 --Jeff

**Comment by kwwall** [comment]
@planetlevel - That was my point exactly.  I brought it up because the
original bug that was described was for this case:

raw ="C:\Documents and Settings\Mario\Desktop\"; 2.
System.out.println(ESAPI. encoder().canonicalize(raw));

I was just tossing in some extra wrinkles.

-kevin
Sent from my Droid; please excuse typos.

**Comment by xeno6696** [comment]
I think probably the user should be [using the file path validator.](http://web.archive.org/web/20160313123526/http://owasp-esapi-java.googlecode.com/svn/trunk_doc/latest/org/owasp/esapi/Validator.html#getValidDirectoryPath%28java.lang.String,%20java.lang.String,%20java.io.File,%20boolean%29) 

I wasn't aware that JavaScript allowed you to escape *every* character.  That's... pretty stupid.

**Comment by planetlevel** [comment]
It’s pretty common for codecs. Like HTML Entities have like a zillion ways to encode ‘a’ -- &#065;, &#x41;, &#x0041; etc etc etc….   here’s an ancient slide you might get a kick out of…

[cid:image001.png@01D1C7D2.E4D8FB60]


 --Jeff

Jeff Williams<https://www.linkedin.com/in/jeffwilliams31337> | CTO
Contrast Security<http://contrastsecurity.com/>
410.707.1487 | @planetlevel @contrastsec
Security for DevOps (IAST<https://www.contrastsecurity.com/iast/what-is-interactive-application-security-testing> + RASP<https://www.contrastsecurity.com/rasp>)

**Comment by xeno6696** [comment]
@planetlevel , the slide didn't come across the email message, will need to attach it to the ticket!  :-)

**Comment by planetlevel** [comment]
![zillionencodings](https://cloud.githubusercontent.com/assets/2704076/16153615/0cef93c0-3475-11e6-90e1-d15c957b6ddb.png)

**Comment by xeno6696** [comment]
I knew about the HTML encodings, but I didn't realize javscript and css also repeated that pattern.

**Comment by kwwall** [comment]
@planetlevel :) That's always been one of my all-time favorite slides. If
that doesn't make an argument for why black-listing is the wrong approach,
then nothing will!

-kevin

**Comment by xeno6696** [comment]
Closing issue.  

```
<script>
var bar = "C:\Documents and Settings\Mario\Desktop\\".normalize();
alert(bar);
</script>
```

returns C:Documents and SettingsMarioDesktop\

The problem here is not with ESAPI but that the user needs to use one of the filepath validation methods instead of `Encoder.canonicalize()`
