### ISSUE TITLE
HTMLEntityCodec.getNamedEntity not case sensitive

### ISSUE THREAD

**Issue by meg23** [ESAPI/esapi-java-legacy#280]
_From [mike.til...@yahoo.com](https://code.google.com/u/109171368508383610253/) on June 26, 2012 12:18:18_

What steps will reproduce the problem? 1.System.out.println(ESAPI.encoder().encodeForHTML(ESAPI.encoder().decodeForHTML("&Alpha; &alpha;"))); What is the expected output? What do you see instead? Expected: &Alpha; &alpha;
Seen: &alpha; &alpha; What version of the product are you using? On what operating system? esapi-2.0.1 Please provide any additional information below. Better to create possible string using given characters, then if no match is found, convert to lower case and try again.

_Original issue: http://code.google.com/p/owasp-esapi-java/issues/detail?id=274_

**Comment by xeno6696** [comment]
Completely invalid issue.  `Α α` is not an HTML entity.

**Comment by xeno6696** [comment]
I was asked for clarification by @kwwall 

Decode for HTML implies that you are handing a string that ought to have HTML entities in it.  Characters that are not entity-encoded should be preserved.  In this case, the behavior works correctly:

```
    public void testDecodeForHTML(){
    	Encoder enc = ESAPI.encoder();
    	assertEquals("Α α", enc.decodeForHTML("Α α"));
    }
```

passes.  

Also, the expectation in the original test case fails, because when handing the encoder `Α α` I would expect `&Alpha; &alpha;` which is exactly what we get:

```
    public void testDecodeForHTML(){
    	Encoder enc = ESAPI.encoder();
    	assertEquals("Α α", enc.decodeForHTML("Α α"));
    	assertEquals("&Alpha; &alpha;", enc.encodeForHTML(enc.decodeForHTML("Α α")));
    }
```

I would never expect encoder to give me back `Α α`.   I expect HTML entities for any character that can be represented as such.
