### ISSUE TITLE
ESAPI validator isValidRedirectLocation does not work

### ISSUE THREAD

**Issue by meg23** [ESAPI/esapi-java-legacy#295]
_From [majorpe...@gmail.com](https://code.google.com/u/104150745622850954138/) on October 26, 2012 06:22:49_

What steps will reproduce the problem? 1. Have a simple code that does an isValidRedirectLocation check What is the expected output? What do you see instead? The test will almost always fail, simply because the built-in Redirect pattern is defined as:
Validator.Redirect=^\/test.*$
Could this be enhanced, so instead a real regexp is used? What version of the product are you using? On what operating system? Does not matter Does this issue affect only a specified browser or set of browsers? No Please provide any additional information below. Since the SecurityWrapperResponse is using the Redirect matching rule as well, probably that fails 99&#37; of the cases as well.

Is using "URL" instead of "Redirect" a valid workaround?

_Original issue: http://code.google.com/p/owasp-esapi-java/issues/detail?id=289_

**Comment by xeno6696** [comment]
That regex is a secure default value, because it is doubtful that `Validator.Redirect` should ever direct to a "test" URL in a production environment.  That property in particular, needs to be configured uniquely for your application.  If it were me, I might even make that default regex one that wouldn't compile.
