### ISSUE TITLE
CSS and images not working with ESAPIWebApplicationFirewallFilter

### ISSUE THREAD

**Issue by meg23** [ESAPI/esapi-java-legacy#296]
_From [shrey.aw...@gmail.com](https://code.google.com/u/115060927877030131697/) on December 03, 2012 13:07:04_

What steps will reproduce the problem? I have integrated ESAPIWebApplicationFirewallFilter in my existing application. Application has started up fine and there is no error in logs but I am not able to see any frames and images on the page only text box is visible, still able to log in to application but again only text is visible after log in.  The application is developed using Spring MVC,
if I change the filter to ESAPIFilter it works fine. What is the expected output? What do you see instead? Expected web page with images and headers, only could see text boxes. What version of the product are you using? On what operating system? 2.0 Does this issue affect only a specified browser or set of browsers? All browsers. Please provide any additional information below.

_Original issue: http://code.google.com/p/owasp-esapi-java/issues/detail?id=290_

**Comment by xeno6696** [comment]
@kwwall There simply isn't enough information here to be able to recreate this issue in the slightest.  Typically I would need 

1.)  Copy of the affected .css file, or snippets OR
2.)  Copy of a small web app demonstrating the problem.  

This sounds to me like they need to customize the AntiSamy file, but there just isn't enough information here to be able to take any action.

**Comment by kwwall** [comment]
@xeno6696 "Closed because there is not sufficient information presented to reproduce the problem" is always a valid reason for closing an issue in my book. It's just too bad that it took us 5 years or so to get to that point.

Perhaps we should add a "Cannot reproduce" label. I thought of using "wontfix" label, but it's not really like we _won't_ fix it, but rather _can't_ because we are lacking sufficient information to reproduce it.

**Comment by xeno6696** [comment]
For tags, I like "insufficient-info"

**Comment by kwwall** [comment]
Works for me. I'll add it.
