### ISSUE TITLE
Eliminate eclipse code warnings to improve quality

### ISSUE THREAD

**Issue by meg23** [ESAPI/esapi-java-legacy#309]
_From [eamonn.w...@gmail.com](https://code.google.com/u/104114803397285871233/) on June 21, 2013 07:53:13_

Hi, I integrated ESAPI into a large legacy application last year and am very happy with it!

However we use eclipse and set all eclipse compiler preferences to Error (instead of Warning or Ignore) for the categories "Potential programming problems" and "Unnecessary code" (except 'value of parameter is not used'). Additionally for JavaDoc 'Malformed Javadoc comments' is also an error.  Altogether this shows 339 "errors" in ESAPI, which include what could be considered bugs (eg potential null pointer access),  efficiency issues (eg boxing and unboxing) and nice-to-haves.

I say all this because it would be nice to see these 'errors' disappear from our eclipse baseline, but it would also improve the quality of the ESAPI deliverable.  If you do not use eclipse I could upload a list of the 339 issues.

Thanks
Eamonn

_Original issue: http://code.google.com/p/owasp-esapi-java/issues/detail?id=303_

**Comment by kwwall** [comment]
I think this one is going to be tedious to fix if we just try to buckle down and tackle it all at once. So instead, this might be one of those that we should try to tackle as we going about other bug fixing activities and hopefully, but then it will get down to something more manageable. (Although, maybe this is a good reason to switch to NetBeans. JK. :) Seriously, I don't generally use Eclipse, but maybe I should start again.  But lets keep an out out for this sort of thing. Thanks all!

**Comment by xeno6696** [comment]
I don't know that we should be attempting to conform to the warnings given by a particular IDE vendor.   

We already use findbugs, I think what we should do is add a couple of plugins, specificaly fb-contrib, and find-sec-bugs.  As a project we agree to adhere to that as our de-facto coding standard.   What makes this better, is that it is triggered by the maven build (mvn findbugs:findbugs) and then that report can be pulled into any number of IDEs.

**Comment by kwwall** [comment]
The problem with any SAST tool is that they find a lot of false positives. Often more false positives than real issues. And even if you can "shut off" those false positives complaints with annotations of some kind, there's always some other favorite SAST tool that finds the same false positives but rely on different annotations to shut them up. (A great example is the use of the term 'password' in a comment or as a variable name; many SAST tools incorrectly identify this as a "hard-coded password".) I've already addressed these findings for all the crypto related code using findbugs, PMD, SWAMP, and HP Fortify but left all the false positives. And since many of those tools do not rely on annotations to shut them (e.g., HP Fortify), there's no way to get rid of them for everyone (sort of sharing say, the analyzed .fpr in the Fortify case, etc.).  And if you add on error checks performed by various IDEs, you have a never ending battle.

The problem with any SAST tool is that they find a lot of false positives. Often more false positives than real issues. And even if you can "shut off" those false positives complaints with annotations of some kind, there's always some other favorite SAST tool that finds the same false positives but rely on different annotations to shut them up. (A great example is the use of the term 'password' in a comment or as a variable name; many SAST tools incorrectly identify this as a "hard-coded password".)

For that reason, I have removed the 'enhancement' label for this and added a 'maintainability' label ('reliability' might be more accurate, but I'm too lazy at the moment to go off and create that new lable) as well as labeling this issue as a low priority. (I was really tempted to add the 'PITA' label as well.)

My impression is that we should be cognizant of "errors" / warnings and fix them when there are actual issues present, and when not, either add the appropriate annotation to suppress them or perhaps mimimally add a comment. But I personally do NOT believe that it is worth the time to methodically go through all such warnings and try to address them in one fell swoop. There are way more important ESAPI bugs to squash.

**Comment by chrisisbeef** [comment]
This. A million times this.

**Comment by xeno6696** [comment]
Going to close this issue.  I don't believe that we should be tying ourselves to reporting on any given SAST tool.

**Comment by kwwall** [comment]
Works for me. My reply to this usually goes something like "if this is important to you, roll up your sleeves, create a PR (preferably in bite-size commits, like ideally one per file), and we will review it, and merge (possibly cherry picking the individual commits). We will revisit this later anyhow as part of the CII Badging effort.
