### ISSUE TITLE
MySQL CODEC : "_" character not handled properly ?

### ISSUE THREAD

**Issue by meg23** [ESAPI/esapi-java-legacy#31]
_From [Mikael.M...@gmail.com](https://code.google.com/u/112394004954344914018/) on July 24, 2009 05:41:04_

The "_" and" &#37;" characters are escaped but http://mirror.yandex.ru/mirrors/ftp.mysql.com/doc/refman/5.0/en/string-syntax.html specifies that these characters have specific behaviours :"If you use “&#37;”
or “\_” outside of pattern-matching contexts, they evaluate to the strings
“&#37;” and “_”, not to “&#37;” and “_”. " 

Example : if we have a table FOO with a row with field VALUE_FOO='TEST_1', 
the SQL command to retrieve this row : SELECT \* FROM FOO WHERE
VALUE_FOO=encodeForSQL('TEST_1') will become : SELECT \* FROM <table> WHERE
<field>='TEST_1' which will not return the row.

_Original issue: http://code.google.com/p/owasp-esapi-java/issues/detail?id=21_

**Comment by drmyersii** [comment]
Where has this thread left off? I'd like to start contributing, but I'm not sure what exactly needs fixed in this issue. Can someone with more domain knowledge elaborate a bit more? Thanks!

**Comment by kwwall** [comment]
David,

I would start with a new Junit test case in CodecTest.java. Maybe something
along the lines that Mikael suggested in his assessment earlier post on
this topic:
-------
Example : if we have a table FOO with a row with field VALUE_FOO='TEST_1',
the SQL command to retrieve this row : SELECT * FROM FOO WHERE
VALUE_FOO=encodeForSQL('TEST_1') will become : SELECT * FROM

WHERE ='TEST_1' which will not return the row.
------
might make a good test case. (See comment earlier in this thread where this
is mentioned.) See if the new test works as expected.  If so, I guess it's
already fixed ( but leave the JUnit test as confirmation.)

It sounds as though it was supposedly fixed in the 1.4 release, but not
maybe not for 2.x, soI if it's broke for your test for 2.xand under the
"develop" branch, then look under the 1.4 Branch in GitHub and look at
either MySQLCodec.java or Codec.java. If it was fixed in 1.4, it would
probably be in one of those files (or perhaps in a config file like
ESAPI.properties).

Hope that helps enough to get your started.

-kevin
Sent from my Droid; please excuse typos.

**Comment by drmyersii** [comment]
That definitely helps! Thanks for the info. I'll get started on this as soon as I can.

**Comment by xeno6696** [comment]
@drm2 where are you at on this?  We're getting ready for a new release.

**Comment by drm2** [comment]
Sorry about the delayed response here. It's obviously been quite some time since I started working on this, and I'm not sure if I'll be able to continue to contribute right now. I will plan to keep watching though, and hopefully I can help out when I get some more bandwidth in the future. 

Thanks!
