### ISSUE TITLE
Construct "&amp;" in Validator.URL is simple character class, not reference to ampersand

### ISSUE THREAD

**Issue by meg23** [ESAPI/esapi-java-legacy#327]
_From [anton.sh...@gmail.com](https://code.google.com/u/113296353901679381202/) on March 17, 2014 16:17:40_

What steps will reproduce the problem? 1. Match a string "a" to a subset of the regex: "^(\/?)([a-zA-Z0-9\-\.\?\,\:\'\/\\\+=&amp;&#37;\$#_]*)?$"
2. Match a string "a" to a subset of the regex without a-z range: "^(\/?)([A-Z0-9\-\.\?\,\:\'\/\\\+=&amp;&#37;\$#_]_)?$"
3. Match a string "a" to a subset of the regex without "amp;" substring: "^(\/?)([A-Z0-9\-\.\?\,\:\'\/\\\+=&&#37;\$#_]_)?$" What is the expected output? What do you see instead? 1. "a" matches
2. "a" matches, but expected not to match, if &amp; is a reference to ampersand
3. "a" does not match

Conclusion: &amp; is a simple character class, not a reference to ampersand. What version of the product are you using? On what operating system? 2.1.0 Win7 Does this issue affect only a specified browser or set of browsers? - Please provide any additional information below. Java 1.6

_Original issue: http://code.google.com/p/owasp-esapi-java/issues/detail?id=322_

**Comment by xeno6696** [comment]
It's unclear here what the exact problem is.  What method are you using?  Validation?  

The likely culprit here is canonicalization, and in 99% of cases where I've seen this problem come up, it's a legitmate problem.  

There's plenty of other missing context on this problem, is the input a URL?  An email address?  

Recommend writing a small web app demonstrating the exact problem with the exact input, with the exact method call.  Otherwise, I recommend closing this issue.

**Comment by kwwall** [comment]
Is what the creator of this issue saying is that the regex for Validator.URL in validation.properties contains '&amp;' rather than '&'? Note that it is within [] and thus a character class. Here's what we have for it:
```
Validator.URL=^(ht|f)tp(s?)\\:\\/\\/[0-9a-zA-Z]([-.\\w]*[0-9a-zA-Z])*(:(0-9)*)*(\\/?)([a-zA-Z0-9\\-\\.\\?\\,\\:\\'\\/\\\\\\+=&amp;%\\$#_]*)?$
```
Is Anton simply stating that instead, it should be:
```
Validator.URL=^(ht|f)tp(s?)\\:\\/\\/[0-9a-zA-Z]([-.\\w]*[0-9a-zA-Z])*(:(0-9)*)*(\\/?)([a-zA-Z0-9\\-\\.\\?\\,\\:\\'\\/\\\\\\+=&%\\$#_]*)?$
```
(or maybe '\&', but I don't think '&' is special within [...]? If so, it would be an easy fix, but note that changing '&amp;' to just '&' would remove ';' so that could be an unintended side-effect so we may need to re-add ';' separately.

Thoughts?

**Comment by xeno6696** [comment]
I'll throw this in unit-test later today.  Your interpretation makes sense, but does ESAPI assume that these regexes are HTML-entity encoded?  (I don't think so, but I'm suspicious now)

**Comment by kwwall** [comment]
I don't believe so either.  I think the regex is likely wrong and should
just be '&'. But not sure off top of my head whether ; will need to be
included. As you say, it needs to start with better unit tests.

-kevin

**Comment by xeno6696** [comment]
Well... I changed `&amp` to `&` and it works fine... of course, the reason it works is because `&amp` already contains the ampersand as well as superfluous `amp` chars already covered.
