### ISSUE TITLE
Regex in ESAPI.properties is not considering few of the french characters

### ISSUE THREAD

**Issue by meg23** [ESAPI/esapi-java-legacy#334]
_From [ragavend...@gmail.com](https://code.google.com/u/108098111221251878390/) on July 08, 2014 10:26:27_

What steps will reproduce the problem? 1. Trying to Add french characters in esapi.properties file for whitelist validation.
2. here is the regex 
^[a-zA-Z0-9.\\-_'!()áéíóúÁÉÍÓÚüÜñÑÀàÂâÆæÇçÈèÉéÊêËëÎîÏïÔôŒœÙùÛûÜüŸÿ«»€,&\\/~"`@#$&#37;*=+\\[\\]:;?©®\\^|\\\\ ]{1,300}$
3. ESAPI is not recognizing €, Œ,œ, Ÿ characters. What is the expected output? What do you see instead? The ESAPI should allow the inputs which has the above french characters.
Instead it is treating them as invalid. When i printed the regex which is validated with, the printed output is not showing these characters. please let me know, if there is any limitation. What version of the product are you using? On what operating system? ESAPI 1.4.4 (bundled with Adobe Cold Fusion 8 security hotfixes), Windows 7 Does this issue affect only a specified browser or set of browsers? N/A Please provide any additional information below.

_Original issue: http://code.google.com/p/owasp-esapi-java/issues/detail?id=331_

**Comment by xeno6696** [comment]
This is because regex metacharacters in JAVA (and in most languages) are valid only over ASCII.  

This was changed in java 1.7 by adding the regex flag `(?u)` which will force regex interpretation across the entire unicode spectrum.  Prior to 1.7, you need to write your regex's more carefully with UNICODE in mind.  

As the Internationalization of any application is incredibly specific to the application, I wouldn't recommend changing default regex's in esapi.  Recommend this issue be closed.

**Comment by kwwall** [comment]
@xeno6696 Agree that this should be closed. However, I will also add a comment in the production & test versions of the ESAPI.properties somewhere to document this. If we had a FAQ, this would be a good thing to place in it as well.
