### ISSUE TITLE
HttpParamtervalue for allowing Xml Data

### ISSUE THREAD

**Issue by meg23** [ESAPI/esapi-java-legacy#337]
_From [bhuvanes...@gmail.com](https://code.google.com/u/115042610881816349684/) on July 14, 2014 14:54:30_

Hi All,

I'm trying to modify the <b>validator.httpParamterValue</b> which is having the value as 
Validator.HTTPParameterValue=^[\\p{L}\\p{N}.\\-/+=_ !$*?@:&#37;]{0,1000}$.

I'm, unable to parse the xml input :
<dataXML><CreateUpdateClient version='1.0'><commonInput></commonInput><client><clientId>JLTF53SR00C</clientId><roleType>Individual</roleType><names><name prodAssoc=''><nameType>Individual</nameType><prefixes>ADM</prefixes><firstName><![CDATA[dasd]]></firstName><middleName><![CDATA[asda]]></middleName><lastName><![CDATA[sdad]]></lastName><suffixes>SR</suffixes><unstructuredName><![CDATA[DDS]]></unstructuredName><action>add</action></name></names></client></CreateUpdateClient><CCreateUpdateClntandRelations1Rsp><messages rc='0'/><clients><client><clientId>JLTF53SR00C</clientId><nameID>00010</nameID></client></clients></CCreateUpdateClntandRelations1Rsp></dataXML>.

Please provide me a regex which would pass the entire input xml for HttpParamter value.

_Original issue: http://code.google.com/p/owasp-esapi-java/issues/detail?id=334_

**Comment by xeno6696** [comment]
What you're asking for is [illegal according to the HTTP 1.1 specification.](http://www.w3.org/Protocols/rfc2616/rfc2616-sec2.html#sec2.2)  Please note that the characters `[` and `<` and `>` are all reserved characters within the HTTP 1.1 spec.  They can only be included in an HTTP header value if they are appropriately escaped with quotes, which is also lacking in the provided input.  

The proper place for HTML/XML content is NOT in an HTTP header.  Re-architect your communication protocol to conform to web standards!  Seriously, as an attacker, I live for finding nonstandard implementations like this, because they're nearly always proprietary and innately exploitable.  Keep HTML/XML content in the request body where they belong.  

@kwwall -- recommend closing.

**Comment by kwwall** [comment]
@xeno6696 is correct, what bhuvanes...@gmail.com is asking for is forbidden by the spec, so we definitely should _NOT_ allow it or otherwise try to support it. An attacker of course can pass whatever "evil" characters that they wish in HTTP request headers, but that doesn't mean that OWASP should do something to encourage developers to accept that.

Am I closing this. #willnotfix
