### ISSUE TITLE
TLD not in Jar

### ISSUE THREAD

**Issue by shimberger** [ESAPI/esapi-java-legacy#365]
According to the release notes the TLD should be packaged in the JAR. However the one I download from http://mvnrepository.com/artifact/org.owasp.esapi/esapi/2.1.0.1 does not have one in it.

**Comment by kwwall** [comment]
Looks like that was mentioned because issue #349 was closed with an expectation of some adjustments and a new issue being opened for it shortly, and I just "scooped it up" as one of the closed issues and tossed it into the summary description of the release notes. In short, my bad. It was closed, but since I was anticipating another issue was going to be opened about it (in fact, issues #212, #213, and #244 are all already similar issues), and I was anticipating a pull request to get it copied from configuration/WEB-INF/esapi.tld to WEB-INF/esapi.tld (or maybe, WEB-INF/resources/esapi.tld) it got dropped in the cracks.

I would expect there is some way to do this in Maven that I'm not aware of. While I'm sure I could figure it out in 'ant', I'm pretty much a Maven newb, so if someone wishes to attach or submit a pull request to fix this (and the other related GitHub issues, mentioned above), one of us will make sure it gets into the next release. As long as you place it somewhere under WEB-INF/ (within reason) I don't care where you place it as long as it is somewhere logical. Thanks,
-kevin

**Comment by shimberger** [comment]
Ok thanks, I found the TLD on GitHub at configuration/META-INF/esapi.tld. It's weirdly missing in the dist.zip.

**Comment by artfullyContrived** [comment]
@kwwall am looking into this but need some clarification. 

Your above comment talks of a WEB-INF directory but I see a META-INF directory instead. 

Was that a mix up or that's how it should be?

**Comment by artfullyContrived** [comment]
@kwwall Your input is required on this.
