### ISSUE TITLE
Build Fails on path with space

### ISSUE THREAD

**Issue by adetlefsen-rms** [ESAPI/esapi-java-legacy#382]
On a completely fresh checkout of ESAPI into a directory path that includes a space, the build fails due to the tests not being able to find the ESAPI configuration files:

```
Running org.owasp.esapi.waf.WAFFilterTest
Attempting to load  as resource file via file I/O.
Not found in 'org.owasp.esapi.resources' directory or file not readable: /Users/august/Documents/Dev Projects/esapi-java-legacy
Not found in SystemResource Directory/resourceDirectory (this should never happen): /Users/august/Documents/Dev%20Projects/esapi-java-legacy/target/test-classes/esapi
Not found in 'user.home' (/Users/august) directory: /Users/august/esapi
Tests run: 28, Failures: 0, Errors: 28, Skipped: 0, Time elapsed: 0.114 sec <<< FAILURE!

```

I think it is because DefaultSecurityConfiguration treats these resources as URLs, and the space is getting URL encoded to %20: 

```
/Users/august/Documents/Dev%20Projects/esapi-java-legacy/target/test-classes/esapi
```

**Comment by kwwall** [comment]
August, I recall Jim Manico have a similar problem to this back when he was project owner, but IIRC, the difference there was that he was doing this on an old WinXP or maybe Vista system where he had a space in his home directory because of the "C:\Documents and Settings\username". I'm a bit fuzzy on that and haven't searched for the bug, but I thought that Jim had fixed it. As far as treating it via a URL does, yes, sometimes it does that and sometimes it uses java.io.File and accesses it that way, returning an InputStream. The URL part generally is intended when searching a jar for a ESAPI.properties resource. So that last part,
`Not found in SystemResource Directory/resourceDirectory (this should never happen): /Users/august/Documents/Dev%20Projects/esapi-java-legacy/target/test-classes/esapi` 
seems actually correct to me. The 4 steps of the search order of how it attempts to find ESAPI.properties is documented in the class documentation for DefaultSecurityConfiguration. (See https://static.javadoc.io/org.owasp.esapi/esapi/2.1.0.1/org/owasp/esapi/reference/DefaultSecurityConfiguration.html for details.)

So which of these 4 steps did you expect it to be found in? And does it do this from running this from a Maven command line or only from an IDE? Any additional information you could provide to add duplicating this (e.g., a new JUnit test for DefaultSecurityConfiguration, etc.) would be helpful.

Thanks,
-kevin

**Comment by adetlefsen-rms** [comment]
For the purpose of the tests, I would argue that you want to only load "known good" configuration files from `src/test/resources`. In that case it could certainly be done as an InputStream from a relative path, which would solve this issue.

Does ESAPI have a built in pattern for overriding `DefaultSecurityConfiguration`?

**Comment by adetlefsen-rms** [comment]
Actually it looks like there is `UnitTestSecurityConfiguration`, but it is only used in a couple of places, and it inherits its method of loading the config files from `DefaultSecurityConfiguration`.

The SecurityConfiguration can be overridden in tests by calling `ESAPI.initialize(impl)`.

**Comment by kwwall** [comment]
I am still able to reproduce this on Linux. It also fails on Windows last time I checked (maybe 4 or so years ago). You get test failures running 'mvn test' when run from a parent directory that has one or more spaces in it.

**Comment by wiiitek** [comment]
I have created a pull request https://github.com/ESAPI/esapi-java-legacy/pull/540 for this issue.
