### ISSUE TITLE
Issues when I am passing htttp://localhost:8080/user=admin&prodversion=no

### ISSUE THREAD

**Issue by nidhinmp** [ESAPI/esapi-java-legacy#395]
When I am passing htttp://localhost:8080/user=admin&prodversion=no 
to String secure = ESAPI.encoder().canonicalize(unsanitizedString) method am getting 
htttp://localhost:8080/user=admin∏version=no  . so it causes redirection error
please look into this

**Comment by planetlevel** [comment]
Hi - this is because @prod; is an HTML entity. Canonicalizer decodes HTML entities that aren't terminated by a semi-colon because some browsers do too.  This is an unfortunate collision of encoding schemes between URL and HTML.  You can change your parameter name or split up the pieces before canonicalizing.

![image](https://user-images.githubusercontent.com/2704076/27389301-0187234e-566c-11e7-9ea8-6a7329fb5ba2.png)

**Comment by xeno6696** [comment]
Actually @planetlevel in resolving #376 I created a new convenience method to be able to safely canonicalize a URL.  It will be available in the next point-release.  

@nidhinmp this behavior is actually working as expected.  URL is a language all by itself, and then your URL contains text that is also an HTML entity.  By definition this is mixed-encoding, so yes we expect this to fail.

**Comment by xeno6696** [comment]
Also @nidhinmp you are making an error in the use of canonicalization!  I would strongly advise against using canonicalized data for anything other than input validation.  In other words, I would never store or otherwise use the canonicalized data.  This can cause very subtle bugs--or in your case, one not so subtle.

**Comment by nidhinmp** [comment]
I am using 

Regarding for above mentioned issue

I am using

DefaultHTTPUtilities secureRedirect=DefaultHTTPUtilities();
secureRedirect.sendRedirect (response,url);

At that time am getting redirect failed exception..
Any other remedy for this...please guide me

**Comment by xeno6696** [comment]
you should be doing something like:

```
String original = "htttp://localhost:8080/user=admin&prodversion=no";

String toValidate = ESAPI.encoder().canonicalize(original);

//Validation logic on toValidate

DefaultHTTPUtilities secureRedirect=DefaultHTTPUtilities();
secureRedirect.sendRedirect (response, original);
```

**Comment by nidhinmp** [comment]
DefaultHTTPUtilities secureRedirect=DefaultHTTPUtilities();
secureRedirect.sendRedirect (response, original);

When we are passing the original URL,  by default canonicalize value is true ... let me know any possible way to make canonicalize value to false
While doing secureRedirect.sendRedirect (response, original);

**Comment by xeno6696** [comment]
So at the moment there isn't any way to service that.  I traced the code path, and it is explictly calling the version of `isValidInput()` that hardcodes to "true" on canonicalize.  

@kwwall -- This uncovered issue looks easy enough to address.  Do you have a problem with adding a convenience method that exposes the send redirect to shut canonicalization off for validation?  Obviously we can supply warnings in the documentation.

**Comment by kwwall** [comment]
@xeno6696 - Not sure I'm following. To me, it looks as though `DefaultHTTPUtilifies.sendRedirect(HttpServletResponse response, String location)` is calling

   ` if (!ESAPI.validator().isValidRedirectLocation("Redirect", location, false)) {`

which calls:
```
    public boolean isValidRedirectLocation(String context, String input, boolean allowNull) throws IntrusionException {
                return ESAPI.validator().isValidInput( context, input, "Redirect", 512, allowNull);
        }
```
in DetaultValidator.java. And that in turn calls,
```
        public boolean isValidInput(String context, String input, String type, int maxLength, boolean allowNull) throws IntrusionException  {
                return isValidInput(context, input, type, maxLength, allowNull, true);
        }
```

where the last boolean 'true' refers to whether or not to canonicalize.

So are you proposing to add a _new_ `DefaultHTTPUtilities.sendRendirect(HttpServletResponse response, String location, boolean canonicalize)` as well as a new `DefaultValidator.isValidRedirectLocation(String context, String input, boolean allowNull, boolean canonicalize)` that it would call (sigh) to support it or something else entirely, such as trying to "fix" the canonicalization look for the ending ';' like @planetlevel referred to by default. If I had to guess, I'd say that probably 99% of the browsers today do the proper thing and look for the trailing ';', so we might consider do something like only keeping the current existing behavior unless there's some (new) property set in the ESAPI.properties file, such as:

        `Validator.supportBrokenBrowserCanonicalization=true`

and we'd make that 'false' by default in the next point release.

BTW, this is reason that I hate the abuse of singletons like ESAPI has. If DefaultValidator were not a singleton, we could add more general setter / getter methods for things like 'allowNull', 'canonicalize', 'maxLenth', etc. and then instead of a kludge to add a new method, we could just do something like this in a new DefaultHTTPUtilities.sendRedirect() method:

```
    public void sendRedirect(HttpServletResponse response, String location. boolean canonicalize) throws AccessControlException, IOException {
        Validator v = ESAPI.validator();
        v.setCanonicalize( canonicalize );
        if ( !v.isValidRedirectLocation("Redirect", location, false) ) {
            logger.fatal(Logger.SECURITY_FAILURE, "Bad redirect location: " + location);
            throw new AccessControlException("Redirect failed", "Bad redirect location: " + location);
        }
        response.sendRedirect(location);
    }
```

or maybe even better, push back the setting of allowNull, canonicalize, maxLength, etc. to either a DefaultHTTPUtilities CTOR or allow them to be set via setter methods.

But IMO, because we have singletons all over, the ESAPI design is more brittle than it ought to be and way too often when we need to make a change in one place it trickles to several other classes.

I guess I'm okay with either approach, but in general, I prefer the more general, extensible solutions rather than ones that specifically address these issues like canonicalization, hard-coded max lengths, etc.
