### ISSUE TITLE
Inkonsistent dependency structure and vulnerable xml (xerces, xalan, xml-apis ...) dependencies

### ISSUE THREAD

**Issue by Lonzak** [ESAPI/esapi-java-legacy#422]
I am using 2.1.0.1 version of esapi and by introducing this dependency, suddenly totally unrelated places broke in my JEE application. After some research the inconsistent maven structure is responsible:
The maven dependency tree looks like that:

![esapidepencies](https://user-images.githubusercontent.com/1830174/30592131-e64968d2-9d45-11e7-80a9-1edfb69b4c74.png)

esapi has 3 XML related compile time dependencies:
xom 1.2.5 -> should be using 1.2.10 and block xalan, xml-apis
antisamy 1.5.3 -> Should use 1.5.6? But in everycase block batik-css 1.7
batik-css 1.8 -> block xml-apis.jar, xml-apis-ext APIs

In the end esapi uses 
Xalan 2.7.0 (CVE-2014-0107) instead of 2.7.2
Xerces 2.8.0 instead of 2.11.0
xml-apis 1.3.03 instead of 1.3.04 or even 1.4.01

Furthermore other vulnerable libs are included e.g.:
commons-fileupload 1.3.1 -> should be using 1.3.3
Vulnerability report for fileupload: https://commons.apache.org/proper/commons-fileupload/security-reports.html

I know that those libraries are only used for specific (not all) ESAPI functions however the pom.xml should be kept as up-to-date as possible.  ESAPI "secretly sneaks" those library into the classpath and thus make the whole application vulnerable.

**Comment by xeno6696** [comment]
@Lonzak thanks for your bug submission!

This problem was dealt with in #381 and will be in the next release.

**Comment by Lonzak** [comment]
Good to hear - is the fix for #381 already in the trunk?
https://github.com/ESAPI/esapi-java-legacy/blob/develop/pom.xml

If so you only went half way:
commons-fileupload 1.3.2 -> should be 1.3.3

and you should block out the old versions:

```
 <dependency>
            <groupId>com.io7m.xom</groupId>
            <artifactId>xom</artifactId>
            <version>1.2.10</version>
            <exclusions>
            	<exclusion>
            		<groupId>xerces</groupId>
            		<artifactId>xercesImpl</artifactId>
            	</exclusion>
            	<exclusion>
            		<groupId>xalan</groupId>
            		<artifactId>xalan</artifactId>
            	</exclusion>
            	<exclusion>
            		<groupId>xml-apis</groupId>
            		<artifactId>xml-apis</artifactId>
            	</exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.beanshell</groupId>
            <artifactId>bsh-core</artifactId>
            <version>2.0b4</version>
        </dependency>
        <dependency>
            <groupId>org.owasp.antisamy</groupId>
            <artifactId>antisamy</artifactId>
            <version>1.5.6</version>
            <exclusions>
            	<exclusion>
            		<groupId>xerces</groupId>
            		<artifactId>xercesImpl</artifactId>
            	</exclusion>
            	<exclusion>
            		<groupId>org.apache.xmlgraphics</groupId>
            		<artifactId>batik-css</artifactId>
            	</exclusion>
            </exclusions>
        </dependency>
```

I attached an examplary pom to show what I mean.

**Comment by Lonzak** [comment]
@xeno6696 
Vote to open this issue again and to fully fix the problem.

**Comment by kwwall** [comment]
It may be awhile until the next official release. We are getting close.

In the meantime, this has already been fixed in the 'develop' branch and
will be in the next release. There was already a GitHub issue about this
that was already closed since it is already in the develop branch.

If you are concerned, build ESAPI yourself using the latest pom.xml from
develop or use the lastest from 'master' and update the pom.xml to use:

xom: 1.2.10
antisamy: 1.5.6
batik-css: 1.9

-kevin
--
Blog: http://off-the-wall-security.blogspot.com/  |  Twitter:  @KevinWWall
NSA: All your crypto bit are belong to us.


On Sep 19, 2017 09:19, "Lonzak" <notifications@github.com> wrote:

I am using 2.1.0.1 version of esapi and by introducing this depency,
suddenly totally unreleated places broke in my JEE application. After some
reasearch the inconsistent maven structure is responsible:
The maven dependency tree looks like that:

[image: esapidepencies]
<https://user-images.githubusercontent.com/1830174/30592131-e64968d2-9d45-11e7-80a9-1edfb69b4c74.png>

esapi has 3 XML related compile time dependencies:
xom 1.2.5 -> should be using 1.2.10 and block xalan, xml-apis
antisamy 1.5.3 -> Should use 1.5.6? But in everycase block batik-css 1.7
batik-css 1.8 -> block xml-apis.jar, xml-apis-ext APIs

In the end esapi uses
Xalan 2.7.0 (CVE-2014-0107) instead of 2.7.2
Xerces 2.8.0 instead of 2.11.0
xml-apis 1.3.03 instead of 1.3.04 or even 1.4.01

Furthermore other vulnerable libs are included e.g.:
commons-fileupload 1.3.1 -> should be using 1.3.3
Vulnerability report for fileupload: https://commons.apache.org/pro
per/commons-fileupload/security-reports.html

I know that those libraries are only used for specific (not all) ESAPI
functions however the pom.xml should be kept as up-to-date as possible.
ESAPI "secretly sneaks" those library into the classpath and thus make the
whole application vulnerable.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ESAPI/esapi-java-legacy/issues/422>, or mute the thread

**Comment by Lonzak** [comment]
@kwwall 
Thanks Kevin for your reply to my initial post. However please also see my 2nd post.

**Comment by kwwall** [comment]
@Lonzak I don't have time to look into this now as I am getting ready to go to AppSec USA. Will try to remember it when I get back.
@xeno6696 If you want to take a look at this in the meantime and make these changes, I trust you to do so. I see that the dependency tree printed by 'mvn dependency:tree' is significantly different than what @Lonzak displayed in the dependency graphic above, so maybe this isn't even needed. I get a bit wary of excluding jars. E.g., concerns that ESAPI might use something in AntiSamy that uses a jar that we have excluded. So what then? But I get his point. Will leave it to you whether we should reopen #381 or not.
