### ISSUE TITLE
DefaultEncoder exhibits "double checked locking" anti-pattern

### ISSUE THREAD

**Issue by douglasheld** [ESAPI/esapi-java-legacy#435]
The constructor for DefaultEncoder creates a singleton with double checked locking. Josh Bloch reported years ago, that this Java source paradigm does not hold up in JVM bytecode the same way it looks to the eye in source code. Ref: https://www.cs.umd.edu/~pugh/java/memoryModel/DoubleCheckedLocking.html

```
        if ( singletonInstance == null ) {
            synchronized ( DefaultEncoder.class ) {
                if ( singletonInstance == null ) {
                    singletonInstance = new DefaultEncoder();
                }
            }
        }
```

Proposed change: don't check for null inside the synchronized block.
OR: move the simplified operation to a new private synchronized method, with something like this:

```
private synchronized void conditionallyCreateSingleton() {
        if ( singletonInstance == null ) {
                    singletonInstance = new DefaultEncoder();
        }
}
```

**Comment by xeno6696** [comment]
Actually the bigger issue itself is the use of Singletons in the first place.  But I joined this project long after that decision was made!

@kwwall @jeremiahjstacey 

Where should we place singleton refactoring on the TODO list?  you've both done this at separate occasions.  I'd say the next major release after our crypto changes?

**Comment by xeno6696** [comment]
Actually, per the article, the double-checked locking could be fixed simply by marking our object as `volatile`.  

Fixing Double-Checked Locking using Volatile
JDK5 and later extends the semantics for volatile so that the system will not allow a write of a volatile to be reordered with respect to any previous read or write, and a read of a volatile cannot be reordered with respect to any following read or write. See this entry in Jeremy Manson's blog for more details.

With this change, the Double-Checked Locking idiom can be made to work by declaring the helper field to be volatile. This does not work under JDK4 and earlier.

```
// Works with acquire/release semantics for volatile // Broken under current semantics for volatile   class Foo {         private volatile Helper helper = null;         public Helper getHelper() {             if (helper == null) {                 synchronized(this) {                     if (helper == null)                         helper = new Helper();                 }             }             return helper;         }     }

```

**Comment by kwwall** [comment]
Matt, you are right about fixing with 'volatile'. That is how @chrisisbeef
fixed the others. If this needs that fix, feel free to make any needed
changes to correct it.

-kevin
--
Blog: http://off-the-wall-security.blogspot.com/  |  Twitter:  @KevinWWall
NSA: All your crypto bit are belong to us.

**Comment by jeremiahjstacey** [comment]
I'm more familiar with the approach presented by Joshua Bloch in 'Effective Java (2nd ed)'  
http://www.informit.com/articles/article.aspx?p=1216151&seqNum=3

I most frequently apply the _singleton with static factory_ when I need to handle a singleton.

```
public class Elvis {
    private static final Elvis INSTANCE = new Elvis();
    private Elvis() { ... }
    public static Elvis getInstance() { return INSTANCE; }

    public void leaveTheBuilding() { ... }
}
```

I have not done extensive testing on the thread safety of this implementation, but I also do not recall ever having a need to.

Just my 2c.

---
in actuality, the implementation I normally use is slightly different than the author's snippet.  I normally have the singleton held within an inner static class of the singleton.  It's been a number of years since the conversation, but I recall that having an impact on the safety during initialization. I don't remember the precise nature of that discussion though.  Below I've updated the original snippet to the format that I use.

```
public class Elvis {
    public static Elvis getInstance() { return ElvisHolder.INSTANCE; }
    private Elvis() { ... }
    public void leaveTheBuilding() { ... }
 
   private static class ElvisHolder {
        private static final Elvis INSTANCE = new Elvis();
   }
}
```

**Comment by douglasheld** [comment]
Considering we are writing security code, I think it would be prudent to sett a good example and use the simplest pattern that would do the job. E.g. the example from Bloch.
Who has studied what unintended features `volatile` would add?

**Comment by kwwall** [comment]
Just an FYI... I think all the other Singleton patterns are using
'volatile'. Personally, I'd like to get rid of the Singleton's completely,
but that's a much bigger task. I plan on doing it for JavaEncryptor, but
not the others yet.

-kevin
--
Blog: http://off-the-wall-security.blogspot.com/  |  Twitter:  @KevinWWall
NSA: All your crypto bit are belong to us.

**Comment by xeno6696** [comment]
“Considering we are writing security code, I think it would be prudent to set a good example and use the simplest pattern that would do the job. ”

I won’t lie, I prefer Bloch’s enum approach, as opposed to both yourself and Jeremiah here.  Which is weird, because I could have sworn Jeremiah TAUGHT me that approach.

Regardless...

Fact is, the Singleton approach *was a bad idea*, and THAT problem trumps the argument of whether we refactor using ‘volatile’ or an enum, or another of Bloch’s suggestions.

@douglasheld , submit a patch if your passion reaches this far.

This is an open issue, but we don’t need critics as much as we need critics committing code!

**Comment by xeno6696** [comment]
> This is an open issue, but we don’t need critics as much as we need critics committing code!

That came off a little heavier than I meant it.  I apologize @douglasheld .

There's two of us "regularly" contributing code to this project.  And I've been trying to get the open issues below 100 for some time.  There's just never enough time...

**Comment by xeno6696** [comment]
So I’m going to close this issue.  The link shared by @Douglasheld is signed by Josh Bloch, and the article states that double-checked locking can be fixed by using the ‘volatile’ keyword after Java 1.5.  I checked the instance used by DefaultEncoder, and it is declared ‘volatile’.  

When doing more research beyond the article, ‘volatile’, I came across this additional interest view with Bloch:

http://www.oracle.com/technetwork/articles/javase/bloch-effective-08-qa-140880.html

“If you need high-performance lazy initializing of an instance field, use the double-check idiom with a volatile field. This idiom wasn't guaranteed to work until release 5.0, when the platform got a new memory model. The idiom is very fast but also complicated and delicate, so don't be tempted to modify it in any way. Just copy and paste -- normally not a good idea, but appropriate here:”

‘’’

// Double-check idiom for lazy initialization of instance fields.
private volatile FieldType field;
FieldType getField() {
    FieldType result = field;
    if (result == null) { // First check (no locking)
        synchronized(this) {
            result = field;
            if (result == null) // Second check (with locking)
                field = result = computeFieldValue();
        }
    }
     return result;
}
‘’’

Here’s our version:

‘’’
private static volatile Encoder singletonInstance;

    public static Encoder getInstance() {
        if ( singletonInstance == null ) {
            synchronized ( DefaultEncoder.class ) {
                if ( singletonInstance == null ) {
                    singletonInstance = new DefaultEncoder();
                }
            }
        }
        return singletonInstance;
    }
‘’’

If it’s guaranteed to work, I’m disinclined to change it. 

Thoughts?

**Comment by xeno6696** [comment]
@crisisbeef, @kwwall, we are deviating a bit from what Bloch recommended as “copy/paste.”  Any history as to why?

**Comment by kwwall** [comment]
@xeno6696 Based on the context of link that you provided, I think that Bloch was referring to a more general lazy initialization of a general field, and not a Singleton pattern. For one, I think it would not be possible for us to perform the synchronization on `this` as that doesn't exist until an instance for the class is constructed via `new DefaultEncoder()` (in our specific case). So we can't use `this` to synchronize on here. Using `DefaultEncoder.class` possibly could be a bit overkill, but it suffices. Also, note that Bloch's example doesn't use the static modifier on his example as he is referring to lazy initialization in general and not just lazy initialization of a class variable so I think that makes sense as well.

I think it is fine to close this, as you previously proposed. When @douglasheld first brought this up, I thought perhaps we had missed the use of the `volatile` modifier in this specific case. However, I will leave it open for further discussion. Do we all agree that it can be closed though?

**Comment by jeremiahjstacey** [comment]
The implementation appears consistent, and I believe that the inner class synchronization guards against the creation race-condition that is a normal concern with this approach.

I feel the issue can be closed.

**Comment by xeno6696** [comment]
@douglasheld that leaves you, amigo, what day you?

**Comment by xeno6696** [comment]
After research, the "double-checked locking" used by ESAPI has been a _**working idiom since Java 1.5**_.  Since we would rather rewrite the library to ignore singletons _entirely_, we're going to close this issue as it doesn't make much sense to write a working idiom away just to remove it when we ditch the singleton model.  However, if anyone feels strongly enough about this to change it anyway, reopen it, fork ESAPI, and submit a PR.
