### ISSUE TITLE
ESAPI 2.2.0.0 release date?

### ISSUE THREAD

**Issue by farmer-x** [ESAPI/esapi-java-legacy#482]
Curious if there has been a release date confirmed/timeline for the updated ESAPI version 2.2.0.0?

**Comment by xeno6696** [comment]
@kwwall I think all we need is the signing key?  I know we've completed the cleanup tasks.

**Comment by kwwall** [comment]
Depends on what you are referring to here. If you are referring to deployed a signed jar, then yes, we would have to obtain a code signing certificate to sign the final jar. That would be ideal, but strictly speaking, it is not necessary. For instance, if you pull down **esapi-2.1.0.1.jar** from Maven Central and run
`jarsigner -verify esapi-2.1.0.1.jar`
it will tell you that the jar is unsigned.

However, what I did sign last time was the "tagged release", version 'esapi-2.1.0.1' using my GPG signing key:
```
$ gpg --list-secret-keys
/home/kww/.gnupg/secring.gpg
----------------------------
sec   2048R/8A2A524F 2016-02-03
uid                  Kevin W. Wall (GitHub signing key) <kevin.w.wall@gmail.com>
```
So in theory, anyone can retrieve that public key from an OpenPGP key server (e.g., keys.gnupg.net) to verify the tagged release. (Of course no one apparently does that? How do I know? Well, I just realized that my public key was not available on any of the public key servers, so it someone had tried to check 2.1.0.1, they never complained at least. Anyway, I just did a
`$ gpg --send-keys 8A2A524F`
so it should make it there eventually.)

Now as far as signing the jar, I could obviously create a self-signed certificate, but that is much less than desirable, but perhaps better than nothing. Most code signing certs you have to pay for though, generally less than $100/year, but the exact amount depends on the issuing CA. Unfortunately, Let's Encrypt does not issue code signing certificates and there's a reasonable possibility that they may never will. But while ESAPI has enough funds for such a certificate, we still need approval to obtain one, although I'm not sure we actually need one. (I am not aware of any other FOSS project that has that. Maybe some mobile code libraries, but it's certainly more of the exception rather than the rule.)

So, no, in all honestly, it's not that that is holding up the 2.2.0.0 release. Rather it is me just trying to figure out what the heck I am doing. I keep getting errors and unfortunately I am not a Maven maven so I'm not sure what I'm doing wrong.

**Comment by kwwall** [comment]
Confirmed GPG signing key for GitHub has been successfully uploaded:
```
$ gpg --recv-keys 8A2A524F
gpg: requesting key 8A2A524F from hkp server keys.gnupg.net
gpg: key 8A2A524F: public key "Kevin W. Wall (GitHub signing key) <kevin.w.wall@gmail.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
```

**Comment by melloware** [comment]
If you need any help let me know I have several open source projects I deploy to Maven Central.

**Comment by kwwall** [comment]
@melloware I know how to create a GPG key (see above). I even know how to use it to create a signed git tagged release ('git tag -u gpgKeyId ...'). The problem is that 'mvn release:prepare' is only creating an UNSIGNED tagged release.

At this point, we are leaning to to all the steps that the Maven 'release' plug-in does manually.

**Comment by melloware** [comment]
Ahh understood didn't know what step you were stuck on.  You are pretty far down the road so hopefully you guys will figure out whats missing!

**Comment by melloware** [comment]
I did notice you were using an older Sonatype parent version 5 when the most up to date release is 7.

```xml
 <groupId>org.sonatype.oss</groupId>
  <artifactId>oss-parent</artifactId>
  <version>9</version>
```

**Comment by bzier** [comment]
Any updates on this?

**Comment by kwwall** [comment]
The detached signatures for the sources and javadoc jars that get uploaded to the Sonatype staging area are failing so I can not 'close' and get stuff moved to Maven Central. I know why it is failing, but just don't know how to fix it. So no date yet. I keep thinking we are really close and then something else pops up. I thought we were going to be done at least a month ago.

**Comment by kwwall** [comment]
@melloware If you're offer of helping with Maven problems is still good, drop me an email at kevin.w.wall @ gmail.com and we can try to collaborate.

**Comment by xeno6696** [comment]
To OP:  today.  Test and have fun!

**Comment by bzier** [comment]
@xeno6696 Can you please provide a link? I don't see it in the releases listed in this repository, and on the page here, I only see RC2: https://mvnrepository.com/artifact/org.owasp.esapi/esapi
I'm probably just looking in the wrong places...

**Comment by kwwall** [comment]
This probably was prematurely closed. The 2.2.0.0-RC2 release candidate is
all we have presently. We are planning on an RC3 in a couple of weeks and
then hopefully the official release.

-kevin
--
Blog: http://off-the-wall-security.blogspot.com/  |  Twitter:  @KevinWWall
NSA: All your crypto bit are belong to us.

**Comment by arcelt** [comment]
@kwwall -- Any idea when we can expect RC3?

**Comment by kwwall** [comment]
Well, I semi-bricked my personal laptop trying to upgrade from Linux Mint
17.3 to 18. Have backups and AFAIK, didn't wipe out anything, but probably
am going to have to do a fresh install (probably to Mint 19.1) That's the
easy part. Installing all the dev tools and customizing those takes a while
though.  So not sure when that will be finished. I've been procrastinating
already for 3 days because getting there is a tedious and boring task. I
may have to rely on my colleagues to get RC3 out the door or at least
merging the couple of PRs we have.

-kevin
--
Blog: http://off-the-wall-security.blogspot.com/  |  Twitter:  @KevinWWall
NSA: All your crypto bit are belong to us.

**Comment by arcelt** [comment]
Sorry to hear about the trouble, @kwwall.  Thanks for keeping us updated.

**Comment by kwwall** [comment]
Well, my laptop is mostly operational, but something (either a newer version of Maven or newer version of the JDK) is causing 40 JUnit tests to fail. It may be related to this mysterious warning from Maven:
```
$ mvn clean
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Scanning for projects...
```
Have tried to debug it yet or even googled for the error since this was when I first tried it. If anyone has some insight, please shoot me an email. Thanks.
