### ISSUE TITLE
Release candidates on maven central

### ISSUE THREAD

**Issue by JoergAdler** [ESAPI/esapi-java-legacy#492]
Hi,

in encoder-esapi version 1.2.1 there is the dependency 

``` 
<dependency>
            <groupId>org.owasp.esapi</groupId>
            <artifactId>esapi</artifactId>
            <version>[2.0,3)</version>
</dependency>
```

This is resolved to 2.2.0.0-RC2 at the moment. Ending up in having a release candidate in my production code. 

Is this intended behavior?

**Comment by kwwall** [comment]
@JoergAdler This is actually a problem with the OWASP Java Encoder project. I reported on this problems here: https://github.com/OWASP/owasp-java-encoder/issues/31

This is not something that we can or will address. IIRC, I think the problem is that the 'encoder-esapi' subproject is using some classes that had been deprecated in ESAPI for a long while that we finally removed.
