### ISSUE TITLE
Maven Install Requires GPG Key

### ISSUE THREAD

**Issue by jeremiahjstacey** [ESAPI/esapi-java-legacy#495]
The process of jar signing, and the requirement of the GPG key, should only be needed when releasing ESAPI.

This may be related to profile changes made during the release effort for 2.2.0.0 official release.

```
$ mvn clean install
[INFO] Scanning for projects...
[INFO]
[INFO] -----------------------< org.owasp.esapi:esapi >------------------------
[INFO] Building ESAPI 2.2.0.0-RC3-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------

[.... compile/test/etc happens ...]

[INFO] --- maven-gpg-plugin:1.6:sign (sign-artifacts) @ esapi ---
gpg: no default secret key: secret key not available
gpg: signing failed: secret key not available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:41 min
[INFO] Finished at: 2019-05-29T20:27:54-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-gpg-plugin:1.6:sign (sign-artifacts) on project esapi: Exit code: 2 -> [Help 1]
[ERROR]
```

**Comment by kwwall** [comment]
@jeremiahjstacey You already mentioned this in a private email, but I thought it would be good to note here for folks that are following along at home.  Using 'mvn package' works fine; it just doesn't copy the jar files from 'target/' to '~/.m2/repository/org/owasp/esapi/esapi/_<release>_/'. But you can manually copy the files so that can serve as a useful workaround.

**Comment by kwwall** [comment]
As per Maven documentation "[Introduction to the Build Lifecycle](https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html)" and "[Lifecycle Reference](https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html#Lifecycle_Reference)", it is not clear whether executing "mvn install" should never require signed jars (in the GPG detached signature sense, not as with "jarsigner"), so it is not clear whether or not this is actually a _bug_ or merely an _annoyance_. Is is though, certainly something that we were not requiring before.

That said, looking at the aforementioned references to the Maven documentation links, it appears as though:

- "mvn package" takes the the compiled code and packages it in its distributable for, such as a jar file.
- "mvn install" installs the package into a _local_ repository, for use as a dependency in other projects locally.
- "mvn deploy" is done in the build environment and copies the final package to the remote repository for sharing with developers and projects.
It also seems evident from this documentation that the Maven build lifecycle phases is generally intended to be done in that order. Because of that, I think that one could argue that if your "mvn deploy" step is to require signed jars (and that seems to be a a requirement of Sonatype's Maven Central Repository rather than Maven itself, although a good one at that), the I think one could argue that one should be doing that in the "mvn install" step as well. (Think a multi-user development server that developers use for staging applications for UAT where you might want signatures to be used and checked like you would in production.)

So, based on that, I think we should **_close_** this. @jeremiahjstacey -- does that work for you, especially since there is a workaround? (I would also point you to the documentation/ESAPI-release-steps.odt document which tells you how to set up an environment for jar signing and I could even show you to have that done automatically if you wish.)

**Comment by jeremiahjstacey** [comment]
I am fine with closing this.  At the time we created this issue we had not intended the GPG Key to be required.  
If we are stating now that ESAPI will only create signed jars, then this task is unnecessary.
@kwwall is there a development guide or other documentation that needs to be updated outside of the release steps?

**Comment by kwwall** [comment]
@jeremiahjstacey Okay. Since you are the one who opened this and are saying we can close it, I'm going to close it on the based that "mvn package" is the way forward. I checked the other documentation, but the only one explicitly mentioning Maven was [ESAPI-Building](https://www.owasp.org/index.php/ESAPI-Building) and it already suggested using "mvn package" rather than "mvn install".
