### ISSUE TITLE
LDAP encoding of slash character

### ISSUE THREAD

**Issue by bdthomsen** [ESAPI/esapi-java-legacy#507]
I have run across references indicating that the slash ('/') character should be encoded for LDAP queries, such as https://docs.microsoft.com/en-us/windows/win32/adsi/search-filter-syntax#special-characters .  Given that there is no harm in doing so, I recommend updating the encodeForLDAP() function to encode the slash character with a "\\2f", in case there are situations where a slash character could be problematic.

**Comment by kwwall** [comment]
@bdthomsen I searched [RFC 2254](https://tools.ietf.org/html/rfc2254) which is the reference that your [ADSI search filter link](https://docs.microsoft.com/en-us/windows/win32/adsi/search-filter-syntax#special-characters) referenced and found no evidence of '/' should be treated as a special character. (The only mention it in the RFC is in the EBNF grammar where it is used as a separator.) Also, that RFC only mentions the 5 characters that we currently quote. I've also searched the referenced RFCs 4710, 4715, and 3377 and '/' seems to hold no special meaning there either.

So, my first question to you is "Are you sure that this is not Microsoft Active Directory Services Interfaces (ADSI) specific search filter criteria rather than general LDAP search filter criteria as defined by the appropriate RFCs?"

And my second question is "If we quote '/' as '\2f', is there _really_ 'no harm in doing so'?" The reason I ask this if there were "no harm" (which I would interpret as "does not change the semantic meaning") of doing this, then why wouldn't we just bother to quote ALL the characters of search criteria? If the potential exists that (for example) someone's existing search criteria exists, then we may have to add a property that only sets encodes the forward slash character for ADSI.
