### ISSUE TITLE
Links in README to users list and dev list are reversed

### ISSUE THREAD

**Issue by davidmichaelkarr** [ESAPI/esapi-java-legacy#523]
Pretty trivial, but the links to the google groups "user" and "dev" lists are reversed.  The link to the user list goes to the dev list, and vice versa.

**Comment by kwwall** [comment]
@davidmichaelkarr Argh! Thanks for letting us know. I can't eve copy-and-paste right. I will get that fixed on the 'master' branch sometime today or tomorrow.

**Comment by kwwall** [comment]
Okay, correction. Only fixing that on the 'develop' list for now (which is what is displayed by default when you visit GitHub). That's because fixing this for 'master' branch would require me to also create the SECURITY.md file, which doesn't yet exist in 'master'. We plan on doing an update to 2.2.0.1 soon, so we will take care of master then.
