### ISSUE TITLE
Configuration flag for disabling Logger User and App Information

### ISSUE THREAD

**Issue by cristiantm** [ESAPI/esapi-java-legacy#527]
We are currently using ESAPI for logger sanitization, but not for authentication. 

We already have auth/app information on logs using MDC. 

Because of that, using ESAPI Logger adds redundant and imprecise information to our logs, as below:

[EVENT SUCCESS **Anonymus:null@unknown -> /com.sample.package.ABC**][msg]

There are more people with the same issue: https://stackoverflow.com/questions/58928401/logs-generated-using-esapi-logger

We are interested on adding extra configurations to ESAPI logger to allow the customization of this. 

We are working on a PR and I´m registering this issue to publish it.

**Comment by kwwall** [comment]
@cristiantm  - I've added a comment that you should read associated with PR #529

**Comment by injecteer** [comment]
added this config in `'org.owasp.esapi:esapi:2.5.0.0'` to ESAPI.properties:
```
# Determines whether ESAPI should log the user info.
Logger.UserInfo=false
# Determines whether ESAPI should log the session id and client IP.
Logger.ClientInfo=false
# Determines whether ESAPI should log the app info.
Logger.AppInfo=false
```
the log output still has the full.-blown class-name:

```
16:34:44.593 [main] INFO  c.z.d.d.w.s.ContextLoaderListener - [EVENT SUCCESS -> /cccc.zzzzzz.dddddd.dddddd.ws.spring.ContextLoaderListener] Applikation-Releaseinformation:
```
Has the PR been removed?

**Comment by kwwall** [comment]
I ultimately will let @jeremiahjstacey respond more fully, but I think the _intent_ with these 3 Logger properties that you show **_not_** to eliminate the fully qualified class names, but to remove logging of the associated authenticated user name (for which you had to really use other ESAPI classes) or the client information (e.g., the session ID and client IP address) and the application name. Specifically, the `Logger.AppInfo` affects whether or not you want the application name (as determined  by `Logger.ApplicationName` in your **ESAPI.properties** file.

Ultimately, it depends on how you are obtaining the ESAPI logger. There are these variations that you could be using:
```java
Logger logger1 = ESAPI.getLogger(Foo.class);
Logger logger2 = ESAPI.getLogger("Foo");
Logger logger3 = ESAPI.log();
```
Of those three, the second one (`logger2`) _should_ not show the fully qualified class name. I would expect the first (`logger1`) _would_ show it. I'd have to chase through the code to see how the last one (`logger3`) would behave, but my guess is that it wouldn't show a FQCN either.

But some of this may depend on the underlying logger that you are using with SLF4J (e.g., Logback, Log4J, etc.) and may also require

**Comment by jeremiahjstacey** [comment]
@kwwall, you're spot-on with your explanation.  Those three properties are used to determine the prefix that is added to logging statement through ESAPI.

The property values are referenced in any one of the `*LogFactory` implementations, and used to configure the [LogPrefixAppender](https://github.com/ESAPI/esapi-java-legacy/blob/develop/src/main/java/org/owasp/esapi/logging/appender/LogPrefixAppender.java)
Setting the values to false remove the additional content that would otherwise be appended by the
- [UserInfoSupplier](https://github.com/ESAPI/esapi-java-legacy/blob/develop/src/main/java/org/owasp/esapi/logging/appender/UserInfoSupplier.java)
- [ClientInfoSupplier](https://github.com/ESAPI/esapi-java-legacy/blob/develop/src/main/java/org/owasp/esapi/logging/appender/ClientInfoSupplier.java)
- [ServerInfoSupplier](https://github.com/ESAPI/esapi-java-legacy/blob/develop/src/main/java/org/owasp/esapi/logging/appender/ServerInfoSupplier.java)

The reference of the fully-qualified class name is based on how the logger was acquired, as you have stated.
