### ISSUE TITLE
ESAPI decodes html entities without trailing ';'

### ISSUE THREAD

**Issue by epic-alex-rodionov** [ESAPI/esapi-java-legacy#577]
When we have this get request: 
https://localhost/campaigns/active?name=cpl%26nima it is converted to 
https://localhost/campaigns/active?name=cpl∋ma and search does not work properly.

After debug I saw HTMLEntityCodec does not properly decodes html entities without trailing ';' in DefaultEncoder line 165:
`%26ni` should not be encoded to `∋`, but only `%26ni;`

**org.owasp.esapi:esapi:2.2.1.1**

**Comment by xeno6696** [comment]
This is working as designed:  the `HTMLEntityCodec` is designed for the worst-case behavior where some browsers improperly render `%26ni` as well as `%26ni;`.

**Comment by xeno6696** [comment]
Further, this is telling me that you're using `DefaultEncoder.canonicalize()` on a URI which has known bad effects.  If you want to properly canonicalize a URI use `DefaultEncoder.getCanonicalizedURI(URI)`.

**Comment by epic-alex-rodionov** [comment]
@xeno6696 we use 
```    @Bean
    public FilterRegistrationBean esapiFilterRegistrationBean() {
        FilterRegistrationBean registrationBean = new FilterRegistrationBean();
        registrationBean.setFilter(esapiSecurityWrapper());
        registrationBean.setName("ESAPISecurityWrapper");
        registrationBean.setOrder(2);
        return registrationBean;
    }```
and property: ESAPI.Encoder=org.owasp.esapi.reference.DefaultEncoder in spring boot
we do not use `DefaultEncoder.canonicalize()` manually

**Comment by xeno6696** [comment]
You're using the `SecurityWrapper` as a kind of single-point XSS filter.  This will be fine as long as you're presenting non-complicated data types.  

This method of XSS filtering is "lowest common denominator."  You won't be able to get URIs to pass without compromising security on more simple data types, as the only "easy solution" would be to remove the HTMLEntityCodec altogether from the canonicalization flow.  

You'll have to treat URI data as the special case it is.  There's no one-size-fits-all that includes URI data--it's not a simple data type.  See [section 3.](https://tools.ietf.org/html/rfc3986)

**Comment by federico-piazza** [comment]
@xeno6696 thanks for your answer. We have turned these both flag off:

```
Encoder.AllowMultipleEncoding=false
Encoder.AllowMixedEncoding=false
```

Shouldn't them disable the char transformation? 

If not, regarding your comment:

>This method of XSS filtering is "lowest common denominator." You won't be able to get URIs to pass without compromising security on more simple data types, as the only "easy solution" would be to remove the HTMLEntityCodec altogether from the canonicalization flow.

We have tried as well removing the HTMLEntityCode from here:

```
Encoder.DefaultCodecList=HTMLEntityCodec,PercentCodec,JavaScriptCodec
            removed this ^^^^^^^^^^
```

But we still face the problem. While debugging we still see the HTML codec is still used.

What do you recommend us to disable these double encoding?

**Comment by xeno6696** [comment]
```
Encoder.AllowMultipleEncoding=false
Encoder.AllowMixedEncoding=false
```

When you do this, you turn off ESAPI's ability to detect if someone is trying to attack your application **GLOBALLY**.  We don't recommend setting this in a live situation.  If you do this, make sure the business sets it in writing that they accept the risk if you deploy it.  _In writing._

> 
> We have tried as well removing the HTMLEntityCode from here:
> 
> Encoder.DefaultCodecList=HTMLEntityCodec,PercentCodec,JavaScriptCodec
>             removed this ^^^^^^^^^^
> But we still face the problem. While debugging we still see the HTML codec is still used.

Interesting.  This then means that the flow through esapi isn't hitting `DefaultEncoder.canonicalize()`  in your instance.  If I were you I'd clone the esapi source and debug through it.  Do you know what method in SecurityWrapper you're hitting?  If you can get me there I should be able to help more.

> What do you recommend us to disable these double encoding?

We don't recommend it.  As I stated above, the root problem is that you're treating URI data like an HTML form field.  Different rules.  URIs are special cases that you can't treat like normal data.  _Anything_ you do to try and make this pass ESAPI **that involves any of the configurations mentioned** _**compromises the security of the rest of your application.**_

**Comment by xeno6696** [comment]
You've got to treat URI data separately from the path you're going down.

**Comment by epic-alex-rodionov** [comment]
@xeno6696 is it possible to disable `SecurityWrapper` to encode/decode request URLs?

**Comment by kwwall** [comment]
For the record, note that this seems somewhat related to issue #503. In particular, @epic-alex-rodionov you might find it useful to review the comments there by @planetlevel

**Comment by planetlevel** [comment]
I haven't looked deeply, but I would think AllowMultipleEncoding and AllowMixedEncoding should be 'true' if you really wanted to disable the checking in canonicalize.  The parameters to canonicalize are for restrictMultiple and restrictMixed, so there are certainly grounds for confusion here.  I agree with Kevin that it's not recommended to disable these.

**Comment by epic-alex-rodionov** [comment]
@xeno6696 mentioned:
_You've got to treat URI data separately from the path you're going down._
How can we do it? Do you have some related settings, examples? Looks like if we use filter `SecurityWrapper` it is not possible to do..

Also about `AllowMultipleEncoding and AllowMixedEncoding` are just validation rules which throw an exception when they are true and warn log they are false.

One more thing: if we use `Encoder.DefaultCodecList=PercentCodec,JavaScriptCodec` (without `HTMLEntityCodec`) - HTMLEntityCodec is still applied to encoding process, I saw it in debug in `DefaultEncoder` line number 165 `working = codec.decode( working );`..

**Comment by kwwall** [comment]
@epic-alex-rodionov - We are aware that Encoder.DefaultCodecList only applies to the ESAPI Validator. The property name is misleading. In hindsight, it probably should have been called Validator.DefaultCodecList. It may have originally been _intended_ to be honored by DefaultEncoder, but the current DefaultEncoder always uses all 3 codecs. in the encoding process.
See https://github.com/ESAPI/esapi-java-legacy/issues/578#issuecomment-725038788 for further details. As I mentioned there, this we _might_ consider a feature request for ESAPI's DefaultEncoder to honor Encode.DefaultCodecList, but since ESAPI's DefaultEncoder is implemented as a singleton, this would affect every use of ESAPI.encoder() in your application, which could be potentially dangerous.

So to try to answer your question "how can we do it?", my question in return is "what specific problem are you trying to solve?" If you--like so many others--are trying to implement a JavaEE servlet filter that works for all as an XSS defense for all situations, it can't (easily) be done. To have that work properly requires knowledge of which contextual XSS output encoding should be used and to do something like that, you'd essentially have to be able to parse all the HTTP response -- so it would need to handle HTML, JavaScript, and CSS at a bare minimum, plus have a knowledge of all possible HTTP response headers. Besides being a huge performance hit, there are ways using multiple encoding to still get XSS payloads through. (If there wasn't ways to bypass detection, then WAFs would have completely solved the XSS problem a while ago. Trust me, they haven't.)

So, please explain exactly what you are trying to do rather than what specific issue (which you've already noted here) you are encountering. It is not just as simple as not decoding (apparent) HTML entities that don't have a trailing ';'.

**Comment by federico-piazza** [comment]
@kwwall (i'm working with @epic-alex-rodionov ).

We use ESAPI in a very basic way. We have a java (spring boot) app and use ESAPI as a java servlet filter (as showed in above Alex's message for `esapiFilterRegistrationBean`).

When the controller (a simple GET endpoint that performs a search by name) is executed, the uri was already manipulated. We want to prevent the manipulation of that URI, we use ESAPI as a request validator.

Regarding your comment `It is not just as simple as not decoding (apparent) HTML entities that don't have a trailing ';'.` it is actually that simple, we are not using ESAPI deeply at all, only as a basic web filter.

Perhaps, we try to use ESAPI for a purpose that is not intended to be used?

**Comment by xeno6696** [comment]
> When the controller (a simple GET endpoint that performs a search by name) is executed, the uri was already manipulated. We want to prevent the manipulation of that URI, we use ESAPI as a request validator.

From what I've put together, you configured the SecurityWrapper filter, which just wraps the java HttpRequest and HttpResponse classes.  

The app receives a GET request.

Then what?  

_What method are you calling?_

**Comment by federico-piazza** [comment]
@xeno6696 sorry the confusion, that's all we do for ESAPI usage, we are not using any ESAPI method manually.

We configure the `org.owasp.esapi.filters.SecurityWrapper` filter, we don't use any method manually. Once the request is caught by the filter, it is manipulated it as described in the thread. 

Then when our controller receives the request (previously handled by the security wrapper), it receives the already manipulated URI.

If you need we can try debugging the ESAPI code and see where the security wrapper is manipulating the URI.

**Comment by kwwall** [comment]
@federico-piazza - Rather than asking "what method are you calling"", I think it would be better to ask what classes / methods (probably SecurityWrapperRequest.getHeader() and/or SecurityResponseRapper.getHeader() if I had to guess) are directly causing this issue?

Because I think the only way to safely deal with this that I can see would be to subclass SecurityWrapperRequest and/or SecurityWrapperResponse classes and override any methods that are causing you problems to valid those special headers with custom code. Then you would have to replace ESAPI's SecurityWrapper class with one of your own that use your new customized extended classes (e.g., CustomizedSecurityWrapperRequest and CustomizedSecurityWrapperResponse) instead of using ESAPI's SecurityWrapperRequest and/or SecurityWrapperResponse classes. [Of course, that causes some possible future maintainence problems, such as if ESAPI fixes something in SecurityWrapper, you'd have to be aware of that and make corresponding fixes in your own code.

In your subclassed SecurityWrapperRequest and/or SecurityWrapperResponse classes you could just ignore the header / parameters that are giving you problems (probably not advisable) or write custom code to deal with it.

But we are not likely to change ESAPI (at least in 2.x) to make it "less safe". As @planetlevel wrote in issue #503 in https://github.com/ESAPI/esapi-java-legacy/issues/503#issuecomment-509724470
`"Our job is not to implement specs. Our job is to protect applications. Browsers, interpreters, and real world parsers do crazy things. They do not stick to specs.  In this case, we have to canonicalize data that doesn’t meet the spec because that’s what browsers do."`

(Maybe in 3.0 we could entertain a mechanism that would let some of the codecs more strictly interpret encoding, so you see 'https://localhost/campaigns/active?name=cpl%26nima', it doesn't get intepreted as 'https://localhost/campaigns/active?name=cpl∋ma', but in 2.x it's really hard to do that selectively since the ESAPI Enoder and Validator are implemented as singletons, meaning it would apply everywhere in every thread which is probably not what you want if you are an application using ESAPI in a more general sense.

If you want someone to 'blame', you can probably 'blame' Jon Postel, who wrote (in reference to TCP/IP) "Be liberal in what you accept, and conservative in what you send". Unfortunately, browsers are liberal in what they accept and attackers have used that to their advantage. In the early days of the Internet, Postel's robustness principle made sense. But in the presence of adversaries, I think it has problems.

**Comment by xeno6696** [comment]
Hold on @kwwall I asked the method call for a reason, it's diagnostic and could point to a bug.  

@federico-piazza 

> Once the request is caught by the filter, it is manipulated it as described in the thread.

How do you know then, if you're not calling any methods?  What field is being manipulated?  Something you did gave you the result `https://localhost/campaigns/active?name=cpl∋ma`

You had to be interacting with _something_ **somewhere**...

**Comment by kwwall** [comment]
It _could_ point to a bug, but I am pretty sure that ESAPI intentionally is decoding things the way that it does. That's how I interpreted Jeff's comment that I referred to. (And I also think that is the correct approach for a security library.)

**Comment by xeno6696** [comment]
> It _could_ point to a bug, but I am pretty sure that ESAPI intentionally is decoding things the way that it does. That's how I interpreted Jeff's comment that I referred to. (And I also think that is the correct approach for a security library.) In other words, my thought is "That's not a bug, that's a feature".

It _could_ be a bug in that when I updated the library for the new method to canonicalize URIs I didn't inspect the SecurityWrapperRequest/Response classes to determine if any methods there needed to go down the correct canonicalization path.  Because we had no unit tests for the class then, so there was nothing to fail to tell me "go fix that."  

In which case, the req/resp pair is using the old method that would generate incorrect results.

I have a deeper issue that the SecurityWrapperRequest object is returning _modified_ data, but this was clearly in place before I ever came on board so we can't just go change it.

**Comment by epic-alex-rodionov** [comment]
@xeno6696 I tried to debug the code:

GET campaigns/experiments?campaign_names=CPL%26Nima goes to 
```
    @Bean
    public Filter esapiSecurityWrapper() {
        return new SecurityWrapper();
    }
```
`SecurityWrapper` calls `chain.doFilter(ESAPI.currentRequest(), ESAPI.currentResponse());`
It calls `SecurityWrapperRequest.getQueryString()` which calls

`clean = ESAPI.validator().getValidInput("HTTP query string: " + query, query, "HTTPQueryString", sc.getIntProp("HttpUtilities.URILENGTH"), true);`

It goes to `StringValidationRule.getValid( String context, String input )` ==> `data = encoder.canonicalize(input);`
```
		if (canonicalizeInput) {
		    data = encoder.canonicalize(input);
		} else {
		    String message = String.format("Input validaiton excludes canonicalization.  Context: %s   Input: %s", context, input);
		    LOGGER.warning(Logger.SECURITY_AUDIT, message);
            data = input;
		}
```
`canonicalizeInput` is true (default value) and looks like we cannot set another value..

Encoder here is `DefaultEncoder.canonicalize( String input, boolean restrictMultiple, boolean restrictMixed )`:

```
...
while( !clean ) {
            clean = true;
            
            // try each codec and keep track of which ones work
            Iterator i = codecs.iterator();
            while ( i.hasNext() ) {
                Codec codec = (Codec)i.next();
                String old = working;
                working = codec.decode( working );
                if ( !old.equals( working ) ) {
                    if ( codecFound != null && codecFound != codec ) {
                        mixedCount++;
                    }
                    codecFound = codec;
                    if ( clean ) {
                        foundCount++;
                    }
                    clean = false;
                }
            }
        }

```

`PercentCodec` converts CPL%26Nima to CPL&Nima and `while( !clean )` we get 2nd iteration when 
`HtmlEntityCodec` converts CPL&Nima to CPL∋ma.

I tried to remove HtmlCodec from `Encoder.DefaultCodecList=HTMLEntityCodec,PercentCodec,JavaScriptCodec`, but it does not work and I see `HTMLEntityCodec` is working in debugger.

**Comment by federico-piazza** [comment]
@xeno6696 @kwwall just to follow up on this one. Is there anything else we can provide?

**Comment by kwwall** [comment]
@federico-piazza - No, I think we have all the details that we need. Perhaps this weekend, if I have some spare cycles--so no promises--I may experiment with some tweaks to get rid of the singletons for the DefaultEncoder and DefaultValidator classes and create a customized ESAPI class (e.g,. something like ExtendedESAPI) that would allow these classes to be customized by tweaking the ESAPI properties that get passed down for them to use. I've already done that for the JavaEncryptor class in a private BitBucket repo forked from our GitHub repo a few years ago, so I know it is doable in a way that preserves backward compatibility. It's just we were hoping to postpone the inevitable "burn the singletons to the ground" until ESAPI 3.0. Just depends how ambitious I get and how much I let football distract me. ;-)  But even then, it likely will not end up in this next point release (which I'm planning before the end of this month) mostly to update some dependencies.
