### ISSUE TITLE
encodeForCSS changes '#' character after upgrading from 2.0.1 to 2.2.1.1

### ISSUE THREAD

**Issue by eddierock1994** [ESAPI/esapi-java-legacy#599]
Input text:  `&#X25;`
In 2.0.1 encodeForCSS used to give the output : \26 \23 X25\3b
In 2.2.1.1 encodeForCSS gives: \26 #X25\3b
`#` does not get encoded anymore.

**Comment by jeremiahjstacey** [comment]
Looking through the changes in the classes involved in the encoding process, I believe the most likely change is line 91 of the current [DefaultEncoder](https://github.com/ESAPI/esapi-java-legacy/blame/develop/src/main/java/org/owasp/esapi/reference/DefaultEncoder.java) implementation.

`private final static char[] IMMUNE_CSS = { '#' };`

This was added in the work done for issue #453 in [this change set](https://github.com/ESAPI/esapi-java-legacy/pull/453/commits/927a5ad9f34601aa7ce4515635f4963e2281398c)

@xeno6696 - I recall you had also looked a bit at the CSS support for RGB values.  What are your thoughts on this?

**Comment by eddierock1994** [comment]
Makes sense. This is the expected behaviour for a colour, however shouldn't '#' be immune only if what follows is a valid colour value?

**Comment by xeno6696** [comment]
@eddierock1994 

> Makes sense. This is the expected behaviour for a colour, however shouldn't '#' be immune only if what follows is a valid colour value?

The encoders/decoders in ESAPI were never intended to do more than single-pass sweeps with zero intelligence.  To do as you suggest would actually be more of a substantial rewrite than you think and directly implies custom parsers for each encoding type.  (I have been proven wrong in the past, but my experience has shown me that this is a kind of issue that grows legs quickly.)  

The 100% correct solution would be absorb this test case into the unit tests, take the hashtag out of the immune list as a more secure default, and **inform anyone who complains that they can subclass the CSS codec, add the immune char themselves.**  Part of why this one slipped through is that I don't think we have a unit test for it and we would have denied #453 if we had it.  Well, I would have.  I'm pretty sure I asked what happens to the unit tests if we removed it.

**Comment by kwwall** [comment]
@eddierock1994 - More info on this decision is written up in GitHub issue #304 if you are interested in the decision making process behind this.

But @xeno6696 is absolutely correct. The "parsers" for the various codecs are really closer to lexers (i.e., lexical analyzers) than to true parsers, having any understanding of what represents anything even remotely resembling a grammar. For that matter, as 'lexers', they also have very limited look-ahead in even what constitutes a lexical 'token' . They are pretty much dirt simple as they can be and still do a decent job. That is, the bottom line for the `CSSCodec`, is that there is **no** _semantic_ understanding at all of the context of what comprises a 'color' in CSS and where that may and may not occur. That is true in general for the other ESAPI `Codec` subclasses as well.

In addition, I believe that this approach is true for most other output encoders that provide defense against XSS, for reasons of speed and simplicity more than any other reason. (Complexity leads to bugs, which leads to vulnerabilities.) Certainly this approach is true for the OWASP Java Encoder as well.

In ESAPI 3, the `Encoder` is not going to be designed as singletons so we _might_ consider a method to add immune characters for a single call to encode something. IMO, that is still very risky because I feel it will be abused by well-meaning developers who may not be AppSec savvy and who are just looking for a quick workaround to fix broken encoding. But at least once we get rid of the singletons, we will have more options. If we tried to support something like that that today, it would at least affect the immune set for that specific codec for _all_ subsequent calls using that particular codec until it was reverted back, so yeah, until then it needs to be intentionally difficult and make devs subclass the appropriate `Codec` class and know how to wire it up if they want to do this.

**Comment by eddierock1994** [comment]
@kwwall After thinking of the solution, it's safe to say that supporting an "intelligent" parser would require a big rewrite. And also agree that adding immune characters to a single call would definitely be abused by devs with a non AppSec background. Thanks for the clarification. Closing this issue. Cheers.
