### ISSUE TITLE
Incorrrect result for `isEnabled()` in `Slf4JLogger`

### ISSUE THREAD

**Issue by sjoshid** [ESAPI/esapi-java-legacy#630]
`isEnabled(int esapiLevel)` in `Slf4JLogger` returns incorrect result. Mostly due to the OR condition `maxLogLevel == Logger.ALL`.

## Steps to reproduce (in 2.2.3.1)
* Create a logger for `SomeClass` in log4j.xml. Set its level to `info` level. Like so:
```
<Logger name="com.SomeClass" level="info">
    <appender-ref ref="SOME-APPENDER-REF"/>
</Logger>
```
* `SomeClass` looks like:
```
private static final Logger LOG = ESAPI.getLogger(SomeClass.class);;
...
if(LOG.isDebugEnabled()) {
    // do some heavy operation here. 
}
```

## Expected result
* With above logger config `LOG.isDebugEnabled()` will return `false`. 

## Actual result
* `LOG.isDebugEnabled()` returns `true`.

## Some more observations
* Even though the enabled checks (like `isDebugEnabled()`, `isInfoEnabled()`, etc.) fail, the actual log statements (like `debug()`, `info()`) do honor the log levels. 
* This has a big perf impact because of all the crap that might go in `LOG.isDebugEnabled()` check.

**Comment by jeremiahjstacey** [comment]
I believe this is valid.  Looking at the documentation for `org.owasp.esapi.Logger.setLevel(int)`
``` 
/**
     * Dynamically set the ESAPI logging severity level. All events of this level and higher will be logged from 
     * this point forward for all logs. All events below this level will be discarded.
     * 
     * @param level The level to set the logging level to. 
     */
```

> All events of this level and higher

This is inversed in the loggers, all of them.  Slf4J, Log4J, and JavaLogger implementations.

```
  private boolean isEnabled(int esapiLevel) {
        //Are Logger.OFF and Logger.ALL reversed?  This should be simply the less than or equal to check...
        return (esapiLevel <= maxLogLevel && maxLogLevel != Logger.OFF) || maxLogLevel == Logger.ALL;
    }
```

The bug is the esapiLevel check, not the OR statement.  The code should read
`esapiLevel >= maxLogLevel`

This makes the naming of the variable `maxLogLevel` a bit confusing, which I think is partly the origin of the problem.
I am suggesting the following:

1. Update the `testLevelEnablement` test implementation for each of the loggers.
These tests are currently expecting the inverse logic behavior and will need to be updated to account.
```
  @Test
    public void testLevelEnablement() {
        testLogger.setLevel(Logger.INFO);

        Assert.assertTrue(testLogger.isFatalEnabled());
        Assert.assertTrue(testLogger.isErrorEnabled());
        Assert.assertTrue(testLogger.isWarningEnabled());
        Assert.assertTrue(testLogger.isInfoEnabled());
        Assert.assertFalse(testLogger.isDebugEnabled());
        Assert.assertFalse(testLogger.isTraceEnabled());

        Assert.assertEquals(Logger.INFO, testLogger.getESAPILevel());
    }
```
2. Rename `maxLogLevel` to `loggingLevel` in each of the logger implementations
* I'm suggesting removing a reference of value associations, as it confuses the intent when doing comparisons against `Logger.OFF` and `Logger.ALL`
3. change the "less than or equal to" check to a "greater than or equal to" in each of the logger implementations

```
  private boolean isEnabled(int esapiLevel) {
        //Are Logger.OFF and Logger.ALL reversed?  This should be simply the less than or equal to check...
        return (esapiLevel >= loggingLevel&& loggingLevel!= Logger.OFF) || loggingLevel== Logger.ALL;
    }
```

There may be other tests that will need to be updated to account, but that should get through the initial updates.

**Comment by sjoshid** [comment]
I dont think we need this `esapiLevel >= loggingLevel` change. Inverse or not depends on which side you are looking from. 

The real question I have in mind is why ESAPI creates its own filter rather than delegating log filtering to concrete log impls. `LOG.info()`, `LOG.debug()` (and its variants) correctly filter events because they are delegated to concrete log impls. But `LOG.isDebugEnabled()` (and its variants) are not. 

If for some reason ESAPI needs its own filtering then `Slf4JLogFactory.getLogger()` should allow clients to set their own `maxLogLevel` and not default it to `Level.ALL` like it does today. I dont think this will scale well though. 

So, easiest (or not) option would be to delegate log filtering to log impls. If not, provide ways to set `maxLogLevel`. Maybe there's a third option Im not thinking of??

**Comment by kwwall** [comment]
@jeremiahjstacey - If we have this backwards (which it sounds like from a
cursory reading of your explanation), should we perhaps just consider
changing the documentation (Javadoc) instead of fixing the code??? We need
to consider the impact of changing this code to the applications using
ESAPI's SLF4J logging in existing code.

I'm not saying it shouldn't be fixed,  but we need to tread carefully here
IF it changes the behavior of what is and isn't logged as many applications
have GRC policies regarding what gets logged. Maybe we need to bring up a
discussion of this on the 2 ESAPI mailing lists and get some feedback from
our user community.

-kevin

**Comment by sjoshid** [comment]
@kwwall 
I dont think simply changing documentation is going to fix it. Most people wont even realize the issue until they do some perf tests.

Here's a little more context to why I opened up this issue.
Before we introduced ESAPI in our code we had something like this. (This isnt normal. Maybe even wrong.)
```
if(LOG.isDebugEnabled()) {
    LOG.info("info level log but under debug enabled check. this feels wrong");
}
```

`LOG.info()` above was never logged.
But after we switched to ESAPI, we start seeing a bunch of logs we had never seen.

Most people will have:
```
if(LOG.isDebugEnabled()) {
    LOG.debug("Correct log level");
}
```

Their logs will stay same but since `LOG.isDebugEnabled()` always returns `true`, all statements inside of that `if` will be hit!!

**Comment by sjoshid** [comment]
Besides that, why does SLF4J factory always assume `maxLogLevel` to be `Level.ALL`?  How do we change it?

**Comment by jeremiahjstacey** [comment]
> I dont think we need this esapiLevel >= loggingLevel change. Inverse or not depends on which side you are looking from.

It does not depend on anything.  The numerical evaluation is inversed and is filtering out logging above the specified level, rather than logging below the specified level.
 
> The real question I have in mind is why ESAPI creates its own filter rather than delegating log filtering to concrete log impls. LOG.info(), LOG.debug() (and its variants) correctly filter events because they are delegated to concrete log impls. But LOG.isDebugEnabled() (and its variants) are not.

The ESAPI library adds additional context around the server and client connection information, as well as providing default handling for log injection attacks.
```
#===========================================================================
# ESAPI Logging
# Set the application name if these logs are combined with other applications
Logger.ApplicationName=ExampleApplication
# If you use an HTML log viewer that does not properly HTML escape log data, you can set LogEncodingRequired to true
Logger.LogEncodingRequired=false
# Determines whether ESAPI should log the application name. This might be clutter in some single-server/single-app environments.
Logger.LogApplicationName=true
# Determines whether ESAPI should log the server IP and port. This might be clutter in some single-server environments.
Logger.LogServerIP=true
# Determines whether ESAPI should log the user info.
Logger.UserInfo=true
# Determines whether ESAPI should log the session id and client IP.
Logger.ClientInfo=true
```

> If for some reason ESAPI needs its own filtering then Slf4JLogFactory.getLogger() should allow clients to set their own maxLogLevel and not default it to Level.ALL like it does today. I dont think this will scale well though.

I would agree with this as a different issue.  The default level of the ESAPI logging should be made into a configuration through ESAPI.properties file, and held with the other logging properties.

As it currently stands, the default of the Level.ALL pushes all of the logs from the ESAPI library into the delegate Logging instance.  If your delegate Logger is configured correctly, you will be able to filter out logs as you would desire.  Again, I am agreeing that the configuration should be extended, but the lack of configuration does not prevent you from achieving the behavior you're requesting -- just at a different level.

> So, easiest (or not) option would be to delegate log filtering to log impls. If not, provide ways to set maxLogLevel. Maybe there's a third option Im not thinking of??

As I stated in my initial response, the field `maxLogLevel` is misnamed and should be addressed as part of this correction to avoid confusion in the future.

> Besides that, why does SLF4J factory always assume maxLogLevel to be Level.ALL? How do we change it?

As stated in the response above.  Level.ALL ensures that all logs are allowed to be propagated to the delegate logger where you are able to achieve the behavior you're looking for.  Once again, restating that I agree that there is an enhancement to be made to extend the configuration to allow the default logging level to be set for the library, and that the logic check for showing the specified level and above (more severe) should be addressed

My previous comment will address the inversed logic check, and we can address the addition of the Default Logging level in issue #631

**Comment by sjoshid** [comment]
That was great explanation. Thanks!
Let's assume you rename the variable and change the the condition _to_
```
(esapiLevel >= loggingLevel&& loggingLevel!= Logger.OFF) || loggingLevel== Logger.ALL;
```

Would it not still return `true` no matter what because of the `|| loggingLevel == Logger.ALL`?? Or you saying #631 will be fixed along with this?

**Comment by jeremiahjstacey** [comment]
@sjoshid Your assessment is correct.  I'm suggesting we use this task to correct the logic first. Fixing this logic error will allow us to appropriately test the impacts of #631 in the course of that work.

Issue #631 may take some time to assess and implement, so I cannot speak to the timeline on that.  In the current implementation of ESAPI, the current hard-coded default setting of `ALL` just forces all of ESAPI's Logger events to the delegate Logging instance.  So if your logging configuration is set up for your system at the level you expect, the ESAPI logs should be filtered or allowed based on your system's configuration.

That should allow some time for the caveats of the configuration extension in #631 to be discussed and implemented.
