### ISSUE TITLE
Removing \ from JSON string by ESAPI.encoder().canonicalize(value)

### ISSUE THREAD

**Issue by bhativikas** [ESAPI/esapi-java-legacy#634]
We are using ESAPI.encoder().canonicalize(value) to fix XSS issues. But the same function is removing \ (backslash) from JSON string.
```
Input String : "textNode":"ABC \"XYZ\""
Output String : "textNode":"ABC "XYZ""
```

Please suggest if any clear solution is available for reference to check the same, so that output string will get \ (backslash) as well.

**Comment by kwwall** [comment]
Can you be a bit more specific about WHY you are taking this approach?

Canonicalization is not output encoding and alone it is not a sufficient
defense against XSS for any context. Instead you should be doing output
encoding in the context in which your JSON will be eventually be rendered.
(If you don't yet know in your application's Java code, then try using
https://github.com/ESAPI/node-esapi.git instead,  which will allow you to
defer that decision to JavaScript.)

-kevin

**Comment by xeno6696** [comment]
This is not a bug because the default configuration of Encoder.canonicalize() is designed specifically to decode HTML, Javascript, and URI percent encoding.  Canonicalization should only be used as the second half of an XSS defense as part of a validation routine.  (called automatically to most calls into the Validator API.)  

It is not recommended to use the canonicalized string for anything other than validation purposes.  Folks will debate this with me, but I advise against storing it entirely.

**Comment by bhativikas** [comment]
I referred the below links and tried to implement the Canonicalization as mentioned. Please suggest what can be alternative for this. Thanks in advance!!

https://www.baeldung.com/spring-prevent-xss
https://github.com/eugenp/tutorials/blob/master/spring-security-modules/spring-5-security/src/main/java/com/baeldung/xss/XSSUtils.java

**Comment by xeno6696** [comment]
The first site is doomed to failure:  It is not possible to write a catch-all filter and intercept or "clean" XSS in this way.  

The second site is also a flawed approach for the exact same reason.  

How to defend against XSS:

https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html

Stated concisely:

1.  Encode data for the context in which you're about to use it for, JUST BEFORE you use it.  
2.  If you want an extra layer of protection, whitelist form inputs for every user-controlled input to the application.  In the case of an application with user-created HTML, use an HTML Sanitizer.  
3. Never use regex as a _**primary**_ defense against XSS.  You will fail.  

The method described in the links you offered are both blacklist approaches and are doomed to a "lowest common denominator" failure if you're attempting to use it across an entire application.

**Comment by kwwall** [comment]
Created https://github.com/eugenp/tutorials/issues/11076 in the hopes this will be addressed.

**Comment by xeno6696** [comment]
One more thing:  Never use JSOUP for sensitive operations.  By default it tries to "correct" invalid HTML, which is useful for browser emulation (perhaps) but it makes life complicated quickly if you're trying to write fine-tuned validation in complex rich-text applications.

**Comment by xeno6696** [comment]
To underline the difficulty of a "catch all" filter like this, imagine the following scenario of an online registration page:

1.  Full Name
2.  Email Address
3.  Phone Number

1. can have spaces and periods to account for "Edna P. Granbo", but can't have special symbols like "@"
2. Requires the "@" symbol unless you've chosen to construct the string yourself on the backend.  
3.  Numbers and hyphens only

Your XSS filter now needs to accept for example, "@" because it's required by 2, even though it's an illegal character in 1&3.  

As you add different fields with different rules that have legality that overlaps with URIs, javascript, and HTML, your XSSFilter by necessity permits just about any of the characters that you want to defend against in almost any application.  (Just imagine an app with finance people who need to have conversations that allow ">" and "<" and it should be instantly clear why a single-point XSS filter requires a level of intelligence about your application that you're probably not willing to try and code for.
