### ISSUE TITLE
ValidationException exposing potentially sensitive user supplied input to log

### ISSUE THREAD

**Issue by mvkendall** [ESAPI/esapi-java-legacy#664]
While Validating HTTP Parameters, and other request data when input validation fails the 'input' and 'orig' input are echoed in ValidationException and visible in application logs.  This prevents a possible exposure of user supplied input that is sensitive in nature.  

For example in StringValidationRule::checkWhitelist 

We are using SecurityWrapperRequest to provide some generalized input validation prior to application specific validation and it is undersirable to log PII or other forms of input data in IntrusionDetection warnings.

**Comment by xeno6696** [comment]
So all `IntrusionException` instances are subclasses  of `java.lang.RuntimeException`

By design, ESAPI will log all `IntrusionException` instances as in cases of actual attack, you want to have the actual input data recorded somewhere.  The choice of subclassing `java.lang.RuntimeException` was deliberate to allow selective choice of when to divert ESAPI's normal logging stream, which is what you desire to do here.  

This means that if you don't want to log the input data, you need to catch the IntrusionException and handle it yourself instead of relying on ESAPI's default behavior.  

This is not a bug.  

As a caution, ensure that when you catch the exception, either the business accepts the risk that you will never know the offending input or you log the attack data in accordance with your industry's guidelines.  For this I recommend a discussion with your security governance, security operations, as well as the business owner who would be responsible for accepting risk.  If the risk is accepted, get it in official writing.  In some regulatory regimes catching and dropping attack data could be interpreted as hiding the fact that you were attacked in the case of an actual breach.

**Comment by kwwall** [comment]
The messages that are logged are Strings, so the best way to treat them is
probably create your own Logger to use with ESAPI and then parse the string
passed in as sensitive data and then mask it or replace or otherwise redact
it. The problem is is there is not any universal way to know what
constitutes sensitive data from that level. For instance, a UUID might just
be a unique opaque identifier in one case, but in some other case it might
represent an authentication token of some sort. If instead of simple
Strings being passed around we'd be better off if it were something that we
could add attributes to, to represent the confidentiality level,  etc. and
then pass those in as separate parameters.

A possible alternative--if your main objective is more concerned with
preventing them from being swept up in your SIEM rather than concern about
individual log files which can be erased or overwritten once
collected--would be to have an aggregator sanitize them. That approach
would probably be easier to roll out,  but might not meet all your use
cases.

But as @xeno6696 wrote, ESAPI is doing what is intended here (even though
we agree we all would still like more), so I agree with him closely this
issue.

However if you would like to make an Enhancement request as a GitHub issue
over in

    https://github.com/ESAPI/esapi-java

(the next version of ESAPI we are designing), we may be able to consider
something like that there.

**Comment by mvkendall** [comment]
> 

Thank you both for the quick responses.

Unfortunately It does appear that one can do as suggested, simply catching the ValidationExceptions, since ValidationExceptions extend EnterpriseSecurityException which adds the exception (per IntrusionDetector.Disable configuration)  to the IntrusionDetector on instance creation.

So in considering the EnterpriseSecurityException docs suggesting the messages should be safe to display and *don't pass in unsanitized data here*  (isn't this violated by including 'orig' value in the message?)  I think the approach can be be to disable the IntrusionDetector and instead perform the logging controlling what is logged in SecurityWrappers which we already have extended in the application.
