### ISSUE TITLE
again .. 

### ISSUE THREAD

**Issue by happylife007** [ESAPI/esapi-java-legacy#757]
https://github.com/ESAPI/esapi-java-legacy/blob/cf4de093ff6b24a00d2e99396522a70b895bbabf/configuration/esapi/ESAPI.properties#L480

**Comment by kwwall** [comment]
@happylife007 - That commit ID references a dependabot PR for updating JUnit and makes no sense in this context as it only touched pom.xml. 'git blame' shows that last change to that line had to do with addressing issue #356, which also doesn't seem particularly relevant here. So, please edit your description (and title) to help us so we can help you. Otherwise, we will be closing this because I can't make any sense out of it as it is. Thanks.

**Comment by happylife007** [comment]
i am sorry .. i discover that my system is under some mask it setup my device and software to a child .. am 46y old  also i found this W3C .. we dont have such rules like this here in Egypt .. so i think that happen personally from someone to have my data specially i use to tread in bitcoin .. i new in all of this but iam learning .. and i hopefully seeking some help .

**Comment by kwwall** [comment]
Alright, no worries. I am going to close this issue based on your reply. If you need assistance on ESAPI, I suggest reaching out on our [GitHub Discussions Q&A](https://github.com/ESAPI/esapi-java-legacy/discussions/categories/q-a) board.

Or, if you do find something wrong with Validator.HTTPHeaderValue, e.g., something that conflicts with the W3C specification for HTTP header values, then please open a new GitHub issue and use the issue template (probably the one for 'bug' in this case). Thanks.
